modLoader="javafml"
loaderVersion="[47,)"
license="https://github.com/DerpyMeow/Hospitals/blob/release/LICENSE"

[[mods]]
modId="hospitals"
version="3.3.0"
displayName="Hospitals (THM Expanded)"
updateJSONURL="https://raw.githubusercontent.com/DerpyMeow/Hospitals/refs/heads/master/UpdateChecker.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hospitals"
logoFile="logo.png"
credits="This Mod Is An Updated And Expanded Version Of Leon90's \"The Hospital Mod\". Original Mod - https://www.curseforge.com/minecraft/mc-mods/the-hospital-mod"
authors="DerpyMeow"
description="This Brings Complex Medical Blocks And Items To Minecraft: Based Off Of Leon90's Mod."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.hospitals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration