modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="hospitals"
version="1.0.0"
displayName="Hospitals (THM Expanded)"
displayURL="https://github.com/DerpyMeow/Hospitals"
logoFile="logo.png"
credits="This Mod Is An Updated And Expanded Version Of Leon90's \"The Hospital Mod\". Original Mod - https://www.curseforge.com/minecraft/mc-mods/the-hospital-mod"
authors="Leon90, DerpyMeow"
description="This Brings Complex Medical Blocks To Minecraft: Based Off Of Leon90's Mod."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.hospitals]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.hospitals]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration