
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.derpymeow.hospitals.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

import net.derpymeow.hospitals.block.XRayMachineBlock;
import net.derpymeow.hospitals.block.XRayLightBlock;
import net.derpymeow.hospitals.block.XRAYLightBoxNeckBlock;
import net.derpymeow.hospitals.block.XRAYLightBoxHandsBlock;
import net.derpymeow.hospitals.block.XRAYLightBoxFeetBlock;
import net.derpymeow.hospitals.block.XRAYLightBoxChestBlock;
import net.derpymeow.hospitals.block.XRAYLightBoxBlankBlock;
import net.derpymeow.hospitals.block.XRAYLightBoxArmsBlock;
import net.derpymeow.hospitals.block.XRAYBuckyStandBlock;
import net.derpymeow.hospitals.block.WorktopWithShelfBlock;
import net.derpymeow.hospitals.block.WorktopBlock;
import net.derpymeow.hospitals.block.WetFloorSignBlock;
import net.derpymeow.hospitals.block.WasteBinDomesticWasteBlock;
import net.derpymeow.hospitals.block.WasteBinClinicalWasteBlock;
import net.derpymeow.hospitals.block.WardStorageDrawersBlock;
import net.derpymeow.hospitals.block.WardResusTrolleyBlock;
import net.derpymeow.hospitals.block.WallStorageTubsYellowBlock;
import net.derpymeow.hospitals.block.WallStorageTubsRedBlock;
import net.derpymeow.hospitals.block.WABlockBlock;
import net.derpymeow.hospitals.block.VinylWallWhiteType1Block;
import net.derpymeow.hospitals.block.VinylWallSalmonType2Block;
import net.derpymeow.hospitals.block.VinylWallRedType1Block;
import net.derpymeow.hospitals.block.VinylWallLightBlueType1Block;
import net.derpymeow.hospitals.block.VinylWallGreyType2Block;
import net.derpymeow.hospitals.block.VinylWallGreyType1Block;
import net.derpymeow.hospitals.block.VinylWallGreenType1Block;
import net.derpymeow.hospitals.block.VinylWallBlueType2Block;
import net.derpymeow.hospitals.block.VinylWallBlueType1Block;
import net.derpymeow.hospitals.block.VinylWallBeigeType2Block;
import net.derpymeow.hospitals.block.VinylWallAquaType2Block;
import net.derpymeow.hospitals.block.VinylWallAquaType1Block;
import net.derpymeow.hospitals.block.VinylFloorWhiteType1Block;
import net.derpymeow.hospitals.block.VinylFloorSalmonType2Block;
import net.derpymeow.hospitals.block.VinylFloorRedType1Block;
import net.derpymeow.hospitals.block.VinylFloorLightBlueType1Block;
import net.derpymeow.hospitals.block.VinylFloorGreyType2Block;
import net.derpymeow.hospitals.block.VinylFloorGreyType1Block;
import net.derpymeow.hospitals.block.VinylFloorGreyBlock;
import net.derpymeow.hospitals.block.VinylFloorGreenType1Block;
import net.derpymeow.hospitals.block.VinylFloorBlueType2Block;
import net.derpymeow.hospitals.block.VinylFloorBlueType1Block;
import net.derpymeow.hospitals.block.VinylFloorBeigeType2Block;
import net.derpymeow.hospitals.block.VinylFloorAquaType2Block;
import net.derpymeow.hospitals.block.VinylFloorAquaType1Block;
import net.derpymeow.hospitals.block.VentilationBlock;
import net.derpymeow.hospitals.block.UltrasoundBlock;
import net.derpymeow.hospitals.block.THBlockBlock;
import net.derpymeow.hospitals.block.SuspendedCeilingBlock;
import net.derpymeow.hospitals.block.SurgicalWorktopTableBlock;
import net.derpymeow.hospitals.block.SurgicalWorkstationBlock;
import net.derpymeow.hospitals.block.SurgicalTrolleyBlock;
import net.derpymeow.hospitals.block.SurgicalRefridgeratedCabinetBlock;
import net.derpymeow.hospitals.block.SurgicalLampBlock;
import net.derpymeow.hospitals.block.SurgicalInstrumentsBlock;
import net.derpymeow.hospitals.block.SurgicalInstrumentTrolleyBlock;
import net.derpymeow.hospitals.block.StoreShelfStockedBlock;
import net.derpymeow.hospitals.block.StoreShelfEmptyBlock;
import net.derpymeow.hospitals.block.SterileWorktopBlock;
import net.derpymeow.hospitals.block.SterileWorkCounterWithShelfBlock;
import net.derpymeow.hospitals.block.SmoothConcreteBlock;
import net.derpymeow.hospitals.block.ScrubSinkBlock;
import net.derpymeow.hospitals.block.RollCageStorageBlock;
import net.derpymeow.hospitals.block.RefridgeratedCentrifugeBlock;
import net.derpymeow.hospitals.block.RedDeskTrayBlock;
import net.derpymeow.hospitals.block.RackShelvingEmptyBlock;
import net.derpymeow.hospitals.block.RackShelvesLinenBlock;
import net.derpymeow.hospitals.block.RABlockBlock;
import net.derpymeow.hospitals.block.PrescriptionShelfBlock;
import net.derpymeow.hospitals.block.PrescriptionBasketEmptyBlock;
import net.derpymeow.hospitals.block.PrescriptionBasketBlock;
import net.derpymeow.hospitals.block.PlasteredWallWhiteBlock;
import net.derpymeow.hospitals.block.PlasteredWallSkyBlueBlock;
import net.derpymeow.hospitals.block.PlasteredWallLimeBlock;
import net.derpymeow.hospitals.block.PlasteredWallGreyBlock;
import net.derpymeow.hospitals.block.PlasteredWallGreenBlock;
import net.derpymeow.hospitals.block.PlasteredWallBlueBlock;
import net.derpymeow.hospitals.block.PlasteredWallBeigeBlock;
import net.derpymeow.hospitals.block.PharmacyCounterwithLogoBlock;
import net.derpymeow.hospitals.block.PharmacyCounterStockedBlock;
import net.derpymeow.hospitals.block.PharmacyCounterBlock;
import net.derpymeow.hospitals.block.PatientInformaitonPointBlock;
import net.derpymeow.hospitals.block.PHBlockBlock;
import net.derpymeow.hospitals.block.OperatingTableBlock;
import net.derpymeow.hospitals.block.OperatingRoomControlPanelBlock;
import net.derpymeow.hospitals.block.OfficeWallPhoneBlock;
import net.derpymeow.hospitals.block.OfficePrinterBlock;
import net.derpymeow.hospitals.block.OfficeDeskWithBackBlock;
import net.derpymeow.hospitals.block.OfficeDeskPhoneBlock;
import net.derpymeow.hospitals.block.OfficeDeskBlock;
import net.derpymeow.hospitals.block.MedicationDrawersBlock;
import net.derpymeow.hospitals.block.MedicalWorkstationCartBlock;
import net.derpymeow.hospitals.block.MedicalGasCeilingMountedBlock;
import net.derpymeow.hospitals.block.MedicalGasAlarmPanelBlock;
import net.derpymeow.hospitals.block.MedicalCrossBlock;
import net.derpymeow.hospitals.block.LifeSupportSyringePumpsBlock;
import net.derpymeow.hospitals.block.LaboratoryFridgeBlock;
import net.derpymeow.hospitals.block.IlluminatedPharmacySignBlock;
import net.derpymeow.hospitals.block.IVStandBlock;
import net.derpymeow.hospitals.block.HospitalBedBlock;
import net.derpymeow.hospitals.block.HeartRateMonitorBlock;
import net.derpymeow.hospitals.block.HandSanitiserDispenserBlock;
import net.derpymeow.hospitals.block.FireExtinguisherBlock;
import net.derpymeow.hospitals.block.FireExitSignWallMountedBlock;
import net.derpymeow.hospitals.block.FireExitSignCeilingMountedBlock;
import net.derpymeow.hospitals.block.FetalMonitoringWorkstationBlock;
import net.derpymeow.hospitals.block.FABlockBlock;
import net.derpymeow.hospitals.block.EPOSCashierSystemBlock;
import net.derpymeow.hospitals.block.DrinksFridgeBlock;
import net.derpymeow.hospitals.block.DecorativeDivideBlock;
import net.derpymeow.hospitals.block.ComputerXRayViewerBlock;
import net.derpymeow.hospitals.block.ComputerScreen2XRAYViewerBlock;
import net.derpymeow.hospitals.block.ComputerScreen2CTScanViewerBlock;
import net.derpymeow.hospitals.block.ComputerCTScanViewerBlock;
import net.derpymeow.hospitals.block.CompoundingIsolatorBlock;
import net.derpymeow.hospitals.block.CleaningTrolleyBlock;
import net.derpymeow.hospitals.block.CladdingStoneEffectBlock;
import net.derpymeow.hospitals.block.CardboardBoxBlock;
import net.derpymeow.hospitals.block.CapsuleFillingMachineBlock;
import net.derpymeow.hospitals.block.BrickRedBlock;
import net.derpymeow.hospitals.block.BrickGreyBlock;
import net.derpymeow.hospitals.block.BrickDarkBlock;
import net.derpymeow.hospitals.block.BrickBeigeBlock;
import net.derpymeow.hospitals.block.BottleFillingMachineBlock;
import net.derpymeow.hospitals.block.BlueDeskTrayBlock;
import net.derpymeow.hospitals.block.BedsideHeadUnitBlock;
import net.derpymeow.hospitals.block.AnalyticalBalanceBlock;
import net.derpymeow.hospitals.block.AnaestheticMachineBlock;
import net.derpymeow.hospitals.HospitalsMod;

public class HospitalsModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(HospitalsMod.MODID);
	public static final DeferredBlock<Block> TH_BLOCK = REGISTRY.register("th_block", THBlockBlock::new);
	public static final DeferredBlock<Block> PH_BLOCK = REGISTRY.register("ph_block", PHBlockBlock::new);
	public static final DeferredBlock<Block> RA_BLOCK = REGISTRY.register("ra_block", RABlockBlock::new);
	public static final DeferredBlock<Block> WA_BLOCK = REGISTRY.register("wa_block", WABlockBlock::new);
	public static final DeferredBlock<Block> FA_BLOCK = REGISTRY.register("fa_block", FABlockBlock::new);
	public static final DeferredBlock<Block> MEDICAL_CROSS = REGISTRY.register("medical_cross", MedicalCrossBlock::new);
	public static final DeferredBlock<Block> ANAESTHETIC_MACHINE = REGISTRY.register("anaesthetic_machine", AnaestheticMachineBlock::new);
	public static final DeferredBlock<Block> SURGICAL_REFRIDGERATED_CABINET = REGISTRY.register("surgical_refridgerated_cabinet", SurgicalRefridgeratedCabinetBlock::new);
	public static final DeferredBlock<Block> SURGICAL_WORKTOP_TABLE = REGISTRY.register("surgical_worktop_table", SurgicalWorktopTableBlock::new);
	public static final DeferredBlock<Block> SURGICAL_INSTRUMENT_TROLLEY = REGISTRY.register("surgical_instrument_trolley", SurgicalInstrumentTrolleyBlock::new);
	public static final DeferredBlock<Block> OPERATING_TABLE = REGISTRY.register("operating_table", OperatingTableBlock::new);
	public static final DeferredBlock<Block> SCRUB_SINK = REGISTRY.register("scrub_sink", ScrubSinkBlock::new);
	public static final DeferredBlock<Block> WALL_STORAGE_TUBS_RED = REGISTRY.register("wall_storage_tubs_red", WallStorageTubsRedBlock::new);
	public static final DeferredBlock<Block> WALL_STORAGE_TUBS_YELLOW = REGISTRY.register("wall_storage_tubs_yellow", WallStorageTubsYellowBlock::new);
	public static final DeferredBlock<Block> SURGICAL_LAMP = REGISTRY.register("surgical_lamp", SurgicalLampBlock::new);
	public static final DeferredBlock<Block> SURGICAL_TROLLEY = REGISTRY.register("surgical_trolley", SurgicalTrolleyBlock::new);
	public static final DeferredBlock<Block> STERILE_WORKTOP = REGISTRY.register("sterile_worktop", SterileWorktopBlock::new);
	public static final DeferredBlock<Block> STERILE_WORK_COUNTER_WITH_SHELF = REGISTRY.register("sterile_work_counter_with_shelf", SterileWorkCounterWithShelfBlock::new);
	public static final DeferredBlock<Block> SURGICAL_WORKSTATION = REGISTRY.register("surgical_workstation", SurgicalWorkstationBlock::new);
	public static final DeferredBlock<Block> OPERATING_ROOM_CONTROL_PANEL = REGISTRY.register("operating_room_control_panel", OperatingRoomControlPanelBlock::new);
	public static final DeferredBlock<Block> SURGICAL_INSTRUMENTS = REGISTRY.register("surgical_instruments", SurgicalInstrumentsBlock::new);
	public static final DeferredBlock<Block> MEDICAL_GAS_CEILING_MOUNTED = REGISTRY.register("medical_gas_ceiling_mounted", MedicalGasCeilingMountedBlock::new);
	public static final DeferredBlock<Block> ILLUMINATED_PHARMACY_SIGN = REGISTRY.register("illuminated_pharmacy_sign", IlluminatedPharmacySignBlock::new);
	public static final DeferredBlock<Block> STORE_SHELF_EMPTY = REGISTRY.register("store_shelf_empty", StoreShelfEmptyBlock::new);
	public static final DeferredBlock<Block> STORE_SHELF_STOCKED = REGISTRY.register("store_shelf_stocked", StoreShelfStockedBlock::new);
	public static final DeferredBlock<Block> COMPOUNDING_ISOLATOR = REGISTRY.register("compounding_isolator", CompoundingIsolatorBlock::new);
	public static final DeferredBlock<Block> ANALYTICAL_BALANCE = REGISTRY.register("analytical_balance", AnalyticalBalanceBlock::new);
	public static final DeferredBlock<Block> REFRIDGERATED_CENTRIFUGE = REGISTRY.register("refridgerated_centrifuge", RefridgeratedCentrifugeBlock::new);
	public static final DeferredBlock<Block> WORKTOP_WITH_SHELF = REGISTRY.register("worktop_with_shelf", WorktopWithShelfBlock::new);
	public static final DeferredBlock<Block> WORKTOP = REGISTRY.register("worktop", WorktopBlock::new);
	public static final DeferredBlock<Block> LABORATORY_FRIDGE = REGISTRY.register("laboratory_fridge", LaboratoryFridgeBlock::new);
	public static final DeferredBlock<Block> CAPSULE_FILLING_MACHINE = REGISTRY.register("capsule_filling_machine", CapsuleFillingMachineBlock::new);
	public static final DeferredBlock<Block> BOTTLE_FILLING_MACHINE = REGISTRY.register("bottle_filling_machine", BottleFillingMachineBlock::new);
	public static final DeferredBlock<Block> MEDICATION_DRAWERS = REGISTRY.register("medication_drawers", MedicationDrawersBlock::new);
	public static final DeferredBlock<Block> PRESCRIPTION_SHELF = REGISTRY.register("prescription_shelf", PrescriptionShelfBlock::new);
	public static final DeferredBlock<Block> EPOS_CASHIER_SYSTEM = REGISTRY.register("epos_cashier_system", EPOSCashierSystemBlock::new);
	public static final DeferredBlock<Block> PRESCRIPTION_BASKET_EMPTY = REGISTRY.register("prescription_basket_empty", PrescriptionBasketEmptyBlock::new);
	public static final DeferredBlock<Block> PRESCRIPTION_BASKET = REGISTRY.register("prescription_basket", PrescriptionBasketBlock::new);
	public static final DeferredBlock<Block> PHARMACY_COUNTER_STOCKED = REGISTRY.register("pharmacy_counter_stocked", PharmacyCounterStockedBlock::new);
	public static final DeferredBlock<Block> PHARMACY_COUNTERWITH_LOGO = REGISTRY.register("pharmacy_counterwith_logo", PharmacyCounterwithLogoBlock::new);
	public static final DeferredBlock<Block> PHARMACY_COUNTER = REGISTRY.register("pharmacy_counter", PharmacyCounterBlock::new);
	public static final DeferredBlock<Block> DECORATIVE_DIVIDE = REGISTRY.register("decorative_divide", DecorativeDivideBlock::new);
	public static final DeferredBlock<Block> ULTRASOUND = REGISTRY.register("ultrasound", UltrasoundBlock::new);
	public static final DeferredBlock<Block> X_RAY_LIGHT = REGISTRY.register("x_ray_light", XRayLightBlock::new);
	public static final DeferredBlock<Block> XRAY_LIGHT_BOX_BLANK = REGISTRY.register("xray_light_box_blank", XRAYLightBoxBlankBlock::new);
	public static final DeferredBlock<Block> XRAY_LIGHT_BOX_CHEST = REGISTRY.register("xray_light_box_chest", XRAYLightBoxChestBlock::new);
	public static final DeferredBlock<Block> XRAY_LIGHT_BOX_FEET = REGISTRY.register("xray_light_box_feet", XRAYLightBoxFeetBlock::new);
	public static final DeferredBlock<Block> XRAY_LIGHT_BOX_HANDS = REGISTRY.register("xray_light_box_hands", XRAYLightBoxHandsBlock::new);
	public static final DeferredBlock<Block> XRAY_LIGHT_BOX_ARMS = REGISTRY.register("xray_light_box_arms", XRAYLightBoxArmsBlock::new);
	public static final DeferredBlock<Block> XRAY_LIGHT_BOX_NECK = REGISTRY.register("xray_light_box_neck", XRAYLightBoxNeckBlock::new);
	public static final DeferredBlock<Block> X_RAY_MACHINE = REGISTRY.register("x_ray_machine", XRayMachineBlock::new);
	public static final DeferredBlock<Block> XRAY_BUCKY_STAND = REGISTRY.register("xray_bucky_stand", XRAYBuckyStandBlock::new);
	public static final DeferredBlock<Block> COMPUTER_CT_SCAN_VIEWER = REGISTRY.register("computer_ct_scan_viewer", ComputerCTScanViewerBlock::new);
	public static final DeferredBlock<Block> COMPUTER_X_RAY_VIEWER = REGISTRY.register("computer_x_ray_viewer", ComputerXRayViewerBlock::new);
	public static final DeferredBlock<Block> COMPUTER_SCREEN_2_CT_SCAN_VIEWER = REGISTRY.register("computer_screen_2_ct_scan_viewer", ComputerScreen2CTScanViewerBlock::new);
	public static final DeferredBlock<Block> COMPUTER_SCREEN_2_XRAY_VIEWER = REGISTRY.register("computer_screen_2_xray_viewer", ComputerScreen2XRAYViewerBlock::new);
	public static final DeferredBlock<Block> BEDSIDE_HEAD_UNIT = REGISTRY.register("bedside_head_unit", BedsideHeadUnitBlock::new);
	public static final DeferredBlock<Block> WARD_STORAGE_DRAWERS = REGISTRY.register("ward_storage_drawers", WardStorageDrawersBlock::new);
	public static final DeferredBlock<Block> FETAL_MONITORING_WORKSTATION = REGISTRY.register("fetal_monitoring_workstation", FetalMonitoringWorkstationBlock::new);
	public static final DeferredBlock<Block> HOSPITAL_BED = REGISTRY.register("hospital_bed", HospitalBedBlock::new);
	public static final DeferredBlock<Block> IV_STAND = REGISTRY.register("iv_stand", IVStandBlock::new);
	public static final DeferredBlock<Block> MEDICAL_WORKSTATION_CART = REGISTRY.register("medical_workstation_cart", MedicalWorkstationCartBlock::new);
	public static final DeferredBlock<Block> LIFE_SUPPORT_SYRINGE_PUMPS = REGISTRY.register("life_support_syringe_pumps", LifeSupportSyringePumpsBlock::new);
	public static final DeferredBlock<Block> HEART_RATE_MONITOR = REGISTRY.register("heart_rate_monitor", HeartRateMonitorBlock::new);
	public static final DeferredBlock<Block> WARD_RESUS_TROLLEY = REGISTRY.register("ward_resus_trolley", WardResusTrolleyBlock::new);
	public static final DeferredBlock<Block> MEDICAL_GAS_ALARM_PANEL = REGISTRY.register("medical_gas_alarm_panel", MedicalGasAlarmPanelBlock::new);
	public static final DeferredBlock<Block> HAND_SANITISER_DISPENSER = REGISTRY.register("hand_sanitiser_dispenser", HandSanitiserDispenserBlock::new);
	public static final DeferredBlock<Block> RACK_SHELVING_EMPTY = REGISTRY.register("rack_shelving_empty", RackShelvingEmptyBlock::new);
	public static final DeferredBlock<Block> RACK_SHELVES_LINEN = REGISTRY.register("rack_shelves_linen", RackShelvesLinenBlock::new);
	public static final DeferredBlock<Block> FIRE_EXIT_SIGN_CEILING_MOUNTED = REGISTRY.register("fire_exit_sign_ceiling_mounted", FireExitSignCeilingMountedBlock::new);
	public static final DeferredBlock<Block> FIRE_EXIT_SIGN_WALL_MOUNTED = REGISTRY.register("fire_exit_sign_wall_mounted", FireExitSignWallMountedBlock::new);
	public static final DeferredBlock<Block> FIRE_EXTINGUISHER = REGISTRY.register("fire_extinguisher", FireExtinguisherBlock::new);
	public static final DeferredBlock<Block> PATIENT_INFORMAITON_POINT = REGISTRY.register("patient_informaiton_point", PatientInformaitonPointBlock::new);
	public static final DeferredBlock<Block> ROLL_CAGE_STORAGE = REGISTRY.register("roll_cage_storage", RollCageStorageBlock::new);
	public static final DeferredBlock<Block> SUSPENDED_CEILING = REGISTRY.register("suspended_ceiling", SuspendedCeilingBlock::new);
	public static final DeferredBlock<Block> VINYL_FLOOR_BLUE_TYPE_1 = REGISTRY.register("vinyl_floor_blue_type_1", VinylFloorBlueType1Block::new);
	public static final DeferredBlock<Block> VINYL_FLOOR_GREY_TYPE_1 = REGISTRY.register("vinyl_floor_grey_type_1", VinylFloorGreyType1Block::new);
	public static final DeferredBlock<Block> VINYL_FLOOR_WHITE_TYPE_1 = REGISTRY.register("vinyl_floor_white_type_1", VinylFloorWhiteType1Block::new);
	public static final DeferredBlock<Block> VINYL_FLOOR_LIGHT_BLUE_TYPE_1 = REGISTRY.register("vinyl_floor_light_blue_type_1", VinylFloorLightBlueType1Block::new);
	public static final DeferredBlock<Block> VINYL_FLOOR_GREEN_TYPE_1 = REGISTRY.register("vinyl_floor_green_type_1", VinylFloorGreenType1Block::new);
	public static final DeferredBlock<Block> VINYL_FLOOR_AQUA_TYPE_1 = REGISTRY.register("vinyl_floor_aqua_type_1", VinylFloorAquaType1Block::new);
	public static final DeferredBlock<Block> VINYL_FLOOR_RED_TYPE_1 = REGISTRY.register("vinyl_floor_red_type_1", VinylFloorRedType1Block::new);
	public static final DeferredBlock<Block> VINYL_WALL_BLUE_TYPE_1 = REGISTRY.register("vinyl_wall_blue_type_1", VinylWallBlueType1Block::new);
	public static final DeferredBlock<Block> VINYL_WALL_GREY_TYPE_1 = REGISTRY.register("vinyl_wall_grey_type_1", VinylWallGreyType1Block::new);
	public static final DeferredBlock<Block> VINYL_WALL_WHITE_TYPE_1 = REGISTRY.register("vinyl_wall_white_type_1", VinylWallWhiteType1Block::new);
	public static final DeferredBlock<Block> VINYL_WALL_LIGHT_BLUE_TYPE_1 = REGISTRY.register("vinyl_wall_light_blue_type_1", VinylWallLightBlueType1Block::new);
	public static final DeferredBlock<Block> VINYL_WALL_GREEN_TYPE_1 = REGISTRY.register("vinyl_wall_green_type_1", VinylWallGreenType1Block::new);
	public static final DeferredBlock<Block> VINYL_WALL_AQUA_TYPE_1 = REGISTRY.register("vinyl_wall_aqua_type_1", VinylWallAquaType1Block::new);
	public static final DeferredBlock<Block> VINYL_WALL_RED_TYPE_1 = REGISTRY.register("vinyl_wall_red_type_1", VinylWallRedType1Block::new);
	public static final DeferredBlock<Block> VINYL_FLOOR_BLUE_TYPE_2 = REGISTRY.register("vinyl_floor_blue_type_2", VinylFloorBlueType2Block::new);
	public static final DeferredBlock<Block> VINYL_FLOOR_BEIGE_TYPE_2 = REGISTRY.register("vinyl_floor_beige_type_2", VinylFloorBeigeType2Block::new);
	public static final DeferredBlock<Block> VINYL_FLOOR_GREY_TYPE_2 = REGISTRY.register("vinyl_floor_grey_type_2", VinylFloorGreyType2Block::new);
	public static final DeferredBlock<Block> VINYL_FLOOR_AQUA_TYPE_2 = REGISTRY.register("vinyl_floor_aqua_type_2", VinylFloorAquaType2Block::new);
	public static final DeferredBlock<Block> VINYL_FLOOR_SALMON_TYPE_2 = REGISTRY.register("vinyl_floor_salmon_type_2", VinylFloorSalmonType2Block::new);
	public static final DeferredBlock<Block> VINYL_WALL_BLUE_TYPE_2 = REGISTRY.register("vinyl_wall_blue_type_2", VinylWallBlueType2Block::new);
	public static final DeferredBlock<Block> VINYL_WALL_BEIGE_TYPE_2 = REGISTRY.register("vinyl_wall_beige_type_2", VinylWallBeigeType2Block::new);
	public static final DeferredBlock<Block> VINYL_WALL_GREY_TYPE_2 = REGISTRY.register("vinyl_wall_grey_type_2", VinylWallGreyType2Block::new);
	public static final DeferredBlock<Block> VINYL_WALL_AQUA_TYPE_2 = REGISTRY.register("vinyl_wall_aqua_type_2", VinylWallAquaType2Block::new);
	public static final DeferredBlock<Block> VINYL_WALL_SALMON_TYPE_2 = REGISTRY.register("vinyl_wall_salmon_type_2", VinylWallSalmonType2Block::new);
	public static final DeferredBlock<Block> BRICK_BEIGE = REGISTRY.register("brick_beige", BrickBeigeBlock::new);
	public static final DeferredBlock<Block> BRICK_GREY = REGISTRY.register("brick_grey", BrickGreyBlock::new);
	public static final DeferredBlock<Block> BRICK_DARK = REGISTRY.register("brick_dark", BrickDarkBlock::new);
	public static final DeferredBlock<Block> BRICK_RED = REGISTRY.register("brick_red", BrickRedBlock::new);
	public static final DeferredBlock<Block> SMOOTH_CONCRETE = REGISTRY.register("smooth_concrete", SmoothConcreteBlock::new);
	public static final DeferredBlock<Block> PLASTERED_WALL_BEIGE = REGISTRY.register("plastered_wall_beige", PlasteredWallBeigeBlock::new);
	public static final DeferredBlock<Block> PLASTERED_WALL_BLUE = REGISTRY.register("plastered_wall_blue", PlasteredWallBlueBlock::new);
	public static final DeferredBlock<Block> PLASTERED_WALL_GREEN = REGISTRY.register("plastered_wall_green", PlasteredWallGreenBlock::new);
	public static final DeferredBlock<Block> PLASTERED_WALL_GREY = REGISTRY.register("plastered_wall_grey", PlasteredWallGreyBlock::new);
	public static final DeferredBlock<Block> PLASTERED_WALL_LIME = REGISTRY.register("plastered_wall_lime", PlasteredWallLimeBlock::new);
	public static final DeferredBlock<Block> PLASTERED_WALL_SKY_BLUE = REGISTRY.register("plastered_wall_sky_blue", PlasteredWallSkyBlueBlock::new);
	public static final DeferredBlock<Block> PLASTERED_WALL_WHITE = REGISTRY.register("plastered_wall_white", PlasteredWallWhiteBlock::new);
	public static final DeferredBlock<Block> VENTILATION = REGISTRY.register("ventilation", VentilationBlock::new);
	public static final DeferredBlock<Block> CARDBOARD_BOX = REGISTRY.register("cardboard_box", CardboardBoxBlock::new);
	public static final DeferredBlock<Block> VINYL_FLOOR_GREY = REGISTRY.register("vinyl_floor_grey", VinylFloorGreyBlock::new);
	public static final DeferredBlock<Block> CLADDING_STONE_EFFECT = REGISTRY.register("cladding_stone_effect", CladdingStoneEffectBlock::new);
	public static final DeferredBlock<Block> BLUE_DESK_TRAY = REGISTRY.register("blue_desk_tray", BlueDeskTrayBlock::new);
	public static final DeferredBlock<Block> RED_DESK_TRAY = REGISTRY.register("red_desk_tray", RedDeskTrayBlock::new);
	public static final DeferredBlock<Block> DRINKS_FRIDGE = REGISTRY.register("drinks_fridge", DrinksFridgeBlock::new);
	public static final DeferredBlock<Block> CLEANING_TROLLEY = REGISTRY.register("cleaning_trolley", CleaningTrolleyBlock::new);
	public static final DeferredBlock<Block> WET_FLOOR_SIGN = REGISTRY.register("wet_floor_sign", WetFloorSignBlock::new);
	public static final DeferredBlock<Block> OFFICE_WALL_PHONE = REGISTRY.register("office_wall_phone", OfficeWallPhoneBlock::new);
	public static final DeferredBlock<Block> OFFICE_DESK_PHONE = REGISTRY.register("office_desk_phone", OfficeDeskPhoneBlock::new);
	public static final DeferredBlock<Block> OFFICE_PRINTER = REGISTRY.register("office_printer", OfficePrinterBlock::new);
	public static final DeferredBlock<Block> OFFICE_DESK = REGISTRY.register("office_desk", OfficeDeskBlock::new);
	public static final DeferredBlock<Block> OFFICE_DESK_WITH_BACK = REGISTRY.register("office_desk_with_back", OfficeDeskWithBackBlock::new);
	public static final DeferredBlock<Block> WASTE_BIN_DOMESTIC_WASTE = REGISTRY.register("waste_bin_domestic_waste", WasteBinDomesticWasteBlock::new);
	public static final DeferredBlock<Block> WASTE_BIN_CLINICAL_WASTE = REGISTRY.register("waste_bin_clinical_waste", WasteBinClinicalWasteBlock::new);
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
