/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.derpymeow.hospitals.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.derpymeow.hospitals.block.XRayMachineBlock;
import net.derpymeow.hospitals.block.XRayLightBlock;
import net.derpymeow.hospitals.block.XRAYLightBoxNeckBlock;
import net.derpymeow.hospitals.block.XRAYLightBoxHandsBlock;
import net.derpymeow.hospitals.block.XRAYLightBoxFeetBlock;
import net.derpymeow.hospitals.block.XRAYLightBoxChestBlock;
import net.derpymeow.hospitals.block.XRAYLightBoxBlankBlock;
import net.derpymeow.hospitals.block.XRAYLightBoxArmsBlock;
import net.derpymeow.hospitals.block.XRAYBuckyStandBlock;
import net.derpymeow.hospitals.block.WorktopWithShelfBlock;
import net.derpymeow.hospitals.block.WorktopBlock;
import net.derpymeow.hospitals.block.WetFloorSignBlock;
import net.derpymeow.hospitals.block.WasteBinDomesticWasteBlock;
import net.derpymeow.hospitals.block.WasteBinClinicalWasteBlock;
import net.derpymeow.hospitals.block.WarningBlock;
import net.derpymeow.hospitals.block.WardStorageDrawersBlock;
import net.derpymeow.hospitals.block.WardResusTrolleyBlock;
import net.derpymeow.hospitals.block.WallStorageTubsYellowBlock;
import net.derpymeow.hospitals.block.WallStorageTubsRedBlock;
import net.derpymeow.hospitals.block.WABlockBlock;
import net.derpymeow.hospitals.block.VinylWallWhiteType1Block;
import net.derpymeow.hospitals.block.VinylWallSalmonType2Block;
import net.derpymeow.hospitals.block.VinylWallRedType1Block;
import net.derpymeow.hospitals.block.VinylWallLightBlueType1Block;
import net.derpymeow.hospitals.block.VinylWallGreyType2Block;
import net.derpymeow.hospitals.block.VinylWallGreyType1Block;
import net.derpymeow.hospitals.block.VinylWallGreenType1Block;
import net.derpymeow.hospitals.block.VinylWallBlueType2Block;
import net.derpymeow.hospitals.block.VinylWallBlueType1Block;
import net.derpymeow.hospitals.block.VinylWallBeigeType2Block;
import net.derpymeow.hospitals.block.VinylWallAquaType2Block;
import net.derpymeow.hospitals.block.VinylWallAquaType1Block;
import net.derpymeow.hospitals.block.VinylFloorWhiteType1Block;
import net.derpymeow.hospitals.block.VinylFloorSalmonType2Block;
import net.derpymeow.hospitals.block.VinylFloorRedType1Block;
import net.derpymeow.hospitals.block.VinylFloorLightBlueType1Block;
import net.derpymeow.hospitals.block.VinylFloorGreyType2Block;
import net.derpymeow.hospitals.block.VinylFloorGreyType1Block;
import net.derpymeow.hospitals.block.VinylFloorGreyBlock;
import net.derpymeow.hospitals.block.VinylFloorGreenType1Block;
import net.derpymeow.hospitals.block.VinylFloorBlueType2Block;
import net.derpymeow.hospitals.block.VinylFloorBlueType1Block;
import net.derpymeow.hospitals.block.VinylFloorBeigeType2Block;
import net.derpymeow.hospitals.block.VinylFloorAquaType2Block;
import net.derpymeow.hospitals.block.VinylFloorAquaType1Block;
import net.derpymeow.hospitals.block.VentilationBlock;
import net.derpymeow.hospitals.block.UltrasoundBlock;
import net.derpymeow.hospitals.block.THBlockBlock;
import net.derpymeow.hospitals.block.SuspendedCeilingBlock;
import net.derpymeow.hospitals.block.SurgicalWorktopTableBlock;
import net.derpymeow.hospitals.block.SurgicalWorkstationBlock;
import net.derpymeow.hospitals.block.SurgicalTrolleyBlock;
import net.derpymeow.hospitals.block.SurgicalRefridgeratedCabinetBlock;
import net.derpymeow.hospitals.block.SurgicalLampBlock;
import net.derpymeow.hospitals.block.SurgicalInstrumentsBlock;
import net.derpymeow.hospitals.block.SurgicalInstrumentTrolleyBlock;
import net.derpymeow.hospitals.block.StoreShelfStockedBlock;
import net.derpymeow.hospitals.block.StoreShelfEmptyBlock;
import net.derpymeow.hospitals.block.SterileWorktopBlock;
import net.derpymeow.hospitals.block.SterileWorkCounterWithShelfBlock;
import net.derpymeow.hospitals.block.SmoothConcreteBlock;
import net.derpymeow.hospitals.block.ScrubSinkBlock;
import net.derpymeow.hospitals.block.RollCageStorageBlock;
import net.derpymeow.hospitals.block.RefridgeratedCentrifugeBlock;
import net.derpymeow.hospitals.block.RedDeskTrayBlock;
import net.derpymeow.hospitals.block.RackShelvingEmptyBlock;
import net.derpymeow.hospitals.block.RackShelvesLinenBlock;
import net.derpymeow.hospitals.block.RABlockBlock;
import net.derpymeow.hospitals.block.PrescriptionShelfBlock;
import net.derpymeow.hospitals.block.PrescriptionBasketEmptyBlock;
import net.derpymeow.hospitals.block.PrescriptionBasketBlock;
import net.derpymeow.hospitals.block.PlasteredWallWhiteBlock;
import net.derpymeow.hospitals.block.PlasteredWallSkyBlueBlock;
import net.derpymeow.hospitals.block.PlasteredWallLimeBlock;
import net.derpymeow.hospitals.block.PlasteredWallGreyBlock;
import net.derpymeow.hospitals.block.PlasteredWallGreenBlock;
import net.derpymeow.hospitals.block.PlasteredWallBlueBlock;
import net.derpymeow.hospitals.block.PlasteredWallBeigeBlock;
import net.derpymeow.hospitals.block.PharmacyCounterwithLogoBlock;
import net.derpymeow.hospitals.block.PharmacyCounterStockedBlock;
import net.derpymeow.hospitals.block.PharmacyCounterBlock;
import net.derpymeow.hospitals.block.PatientInformaitonPointBlock;
import net.derpymeow.hospitals.block.PHBlockBlock;
import net.derpymeow.hospitals.block.OperatingTableBlock;
import net.derpymeow.hospitals.block.OperatingRoomControlPanelBlock;
import net.derpymeow.hospitals.block.OfficeWallPhoneBlock;
import net.derpymeow.hospitals.block.OfficePrinterBlock;
import net.derpymeow.hospitals.block.OfficeDeskWithBackBlock;
import net.derpymeow.hospitals.block.OfficeDeskPhoneBlock;
import net.derpymeow.hospitals.block.OfficeDeskBlock;
import net.derpymeow.hospitals.block.MixedBloodBlock;
import net.derpymeow.hospitals.block.MiniTilesBlock;
import net.derpymeow.hospitals.block.MedicationDrawersBlock;
import net.derpymeow.hospitals.block.MedicalWorkstationCartBlock;
import net.derpymeow.hospitals.block.MedicalGasCeilingMountedBlock;
import net.derpymeow.hospitals.block.MedicalGasAlarmPanelBlock;
import net.derpymeow.hospitals.block.MedicalCrossBlock;
import net.derpymeow.hospitals.block.LightBlockBlock;
import net.derpymeow.hospitals.block.LifeSupportSyringePumpsBlock;
import net.derpymeow.hospitals.block.LargelightbluetilesBlock;
import net.derpymeow.hospitals.block.LargedarktilesBlock;
import net.derpymeow.hospitals.block.Labtiles4Block;
import net.derpymeow.hospitals.block.Labtiles3Block;
import net.derpymeow.hospitals.block.Labtiles2Block;
import net.derpymeow.hospitals.block.Labtiles1Block;
import net.derpymeow.hospitals.block.LaboratoryFridgeBlock;
import net.derpymeow.hospitals.block.IlluminatedPharmacySignBlock;
import net.derpymeow.hospitals.block.IVStandBlock;
import net.derpymeow.hospitals.block.HospitalBedBlock;
import net.derpymeow.hospitals.block.HeartRateMonitorBlock;
import net.derpymeow.hospitals.block.HandSanitiserDispenserBlock;
import net.derpymeow.hospitals.block.FireExtinguisherBlock;
import net.derpymeow.hospitals.block.FireExitSignWallMountedBlock;
import net.derpymeow.hospitals.block.FireExitSignCeilingMountedBlock;
import net.derpymeow.hospitals.block.FetalMonitoringWorkstationBlock;
import net.derpymeow.hospitals.block.FABlockBlock;
import net.derpymeow.hospitals.block.EPOSCashierSystemBlock;
import net.derpymeow.hospitals.block.DrinksFridgeBlock;
import net.derpymeow.hospitals.block.DecorativeDivideBlock;
import net.derpymeow.hospitals.block.Darklabtiles2Block;
import net.derpymeow.hospitals.block.Darklabtiles1Block;
import net.derpymeow.hospitals.block.ComputerXRayViewerBlock;
import net.derpymeow.hospitals.block.ComputerScreen2XRAYViewerBlock;
import net.derpymeow.hospitals.block.ComputerScreen2CTScanViewerBlock;
import net.derpymeow.hospitals.block.ComputerCTScanViewerBlock;
import net.derpymeow.hospitals.block.CompoundingIsolatorBlock;
import net.derpymeow.hospitals.block.CleaningTrolleyBlock;
import net.derpymeow.hospitals.block.CladdingStoneEffectBlock;
import net.derpymeow.hospitals.block.CardboardBoxBlock;
import net.derpymeow.hospitals.block.CapsuleFillingMachineBlock;
import net.derpymeow.hospitals.block.BrickRedBlock;
import net.derpymeow.hospitals.block.BrickGreyBlock;
import net.derpymeow.hospitals.block.BrickDarkBlock;
import net.derpymeow.hospitals.block.BrickBeigeBlock;
import net.derpymeow.hospitals.block.BottleFillingMachineBlock;
import net.derpymeow.hospitals.block.BlueDeskTrayBlock;
import net.derpymeow.hospitals.block.BloodCentrifugeBlock;
import net.derpymeow.hospitals.block.BlockOfStainlessSteelBlock;
import net.derpymeow.hospitals.block.BedsideHeadUnitBlock;
import net.derpymeow.hospitals.block.AnalyticalBalanceBlock;
import net.derpymeow.hospitals.block.AnaestheticMachineBlock;
import net.derpymeow.hospitals.HospitalsMod;

public class HospitalsModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, HospitalsMod.MODID);
	public static final RegistryObject<Block> TH_BLOCK = REGISTRY.register("th_block", () -> new THBlockBlock());
	public static final RegistryObject<Block> PH_BLOCK = REGISTRY.register("ph_block", () -> new PHBlockBlock());
	public static final RegistryObject<Block> RA_BLOCK = REGISTRY.register("ra_block", () -> new RABlockBlock());
	public static final RegistryObject<Block> WA_BLOCK = REGISTRY.register("wa_block", () -> new WABlockBlock());
	public static final RegistryObject<Block> FA_BLOCK = REGISTRY.register("fa_block", () -> new FABlockBlock());
	public static final RegistryObject<Block> MEDICAL_CROSS = REGISTRY.register("medical_cross", () -> new MedicalCrossBlock());
	public static final RegistryObject<Block> ANAESTHETIC_MACHINE = REGISTRY.register("anaesthetic_machine", () -> new AnaestheticMachineBlock());
	public static final RegistryObject<Block> SURGICAL_REFRIDGERATED_CABINET = REGISTRY.register("surgical_refridgerated_cabinet", () -> new SurgicalRefridgeratedCabinetBlock());
	public static final RegistryObject<Block> SURGICAL_WORKTOP_TABLE = REGISTRY.register("surgical_worktop_table", () -> new SurgicalWorktopTableBlock());
	public static final RegistryObject<Block> SURGICAL_INSTRUMENT_TROLLEY = REGISTRY.register("surgical_instrument_trolley", () -> new SurgicalInstrumentTrolleyBlock());
	public static final RegistryObject<Block> OPERATING_TABLE = REGISTRY.register("operating_table", () -> new OperatingTableBlock());
	public static final RegistryObject<Block> SCRUB_SINK = REGISTRY.register("scrub_sink", () -> new ScrubSinkBlock());
	public static final RegistryObject<Block> WALL_STORAGE_TUBS_RED = REGISTRY.register("wall_storage_tubs_red", () -> new WallStorageTubsRedBlock());
	public static final RegistryObject<Block> WALL_STORAGE_TUBS_YELLOW = REGISTRY.register("wall_storage_tubs_yellow", () -> new WallStorageTubsYellowBlock());
	public static final RegistryObject<Block> SURGICAL_LAMP = REGISTRY.register("surgical_lamp", () -> new SurgicalLampBlock());
	public static final RegistryObject<Block> SURGICAL_TROLLEY = REGISTRY.register("surgical_trolley", () -> new SurgicalTrolleyBlock());
	public static final RegistryObject<Block> STERILE_WORKTOP = REGISTRY.register("sterile_worktop", () -> new SterileWorktopBlock());
	public static final RegistryObject<Block> STERILE_WORK_COUNTER_WITH_SHELF = REGISTRY.register("sterile_work_counter_with_shelf", () -> new SterileWorkCounterWithShelfBlock());
	public static final RegistryObject<Block> SURGICAL_WORKSTATION = REGISTRY.register("surgical_workstation", () -> new SurgicalWorkstationBlock());
	public static final RegistryObject<Block> OPERATING_ROOM_CONTROL_PANEL = REGISTRY.register("operating_room_control_panel", () -> new OperatingRoomControlPanelBlock());
	public static final RegistryObject<Block> SURGICAL_INSTRUMENTS = REGISTRY.register("surgical_instruments", () -> new SurgicalInstrumentsBlock());
	public static final RegistryObject<Block> MEDICAL_GAS_CEILING_MOUNTED = REGISTRY.register("medical_gas_ceiling_mounted", () -> new MedicalGasCeilingMountedBlock());
	public static final RegistryObject<Block> ILLUMINATED_PHARMACY_SIGN = REGISTRY.register("illuminated_pharmacy_sign", () -> new IlluminatedPharmacySignBlock());
	public static final RegistryObject<Block> STORE_SHELF_EMPTY = REGISTRY.register("store_shelf_empty", () -> new StoreShelfEmptyBlock());
	public static final RegistryObject<Block> STORE_SHELF_STOCKED = REGISTRY.register("store_shelf_stocked", () -> new StoreShelfStockedBlock());
	public static final RegistryObject<Block> COMPOUNDING_ISOLATOR = REGISTRY.register("compounding_isolator", () -> new CompoundingIsolatorBlock());
	public static final RegistryObject<Block> ANALYTICAL_BALANCE = REGISTRY.register("analytical_balance", () -> new AnalyticalBalanceBlock());
	public static final RegistryObject<Block> REFRIDGERATED_CENTRIFUGE = REGISTRY.register("refridgerated_centrifuge", () -> new RefridgeratedCentrifugeBlock());
	public static final RegistryObject<Block> WORKTOP_WITH_SHELF = REGISTRY.register("worktop_with_shelf", () -> new WorktopWithShelfBlock());
	public static final RegistryObject<Block> WORKTOP = REGISTRY.register("worktop", () -> new WorktopBlock());
	public static final RegistryObject<Block> LABORATORY_FRIDGE = REGISTRY.register("laboratory_fridge", () -> new LaboratoryFridgeBlock());
	public static final RegistryObject<Block> CAPSULE_FILLING_MACHINE = REGISTRY.register("capsule_filling_machine", () -> new CapsuleFillingMachineBlock());
	public static final RegistryObject<Block> BOTTLE_FILLING_MACHINE = REGISTRY.register("bottle_filling_machine", () -> new BottleFillingMachineBlock());
	public static final RegistryObject<Block> MEDICATION_DRAWERS = REGISTRY.register("medication_drawers", () -> new MedicationDrawersBlock());
	public static final RegistryObject<Block> PRESCRIPTION_SHELF = REGISTRY.register("prescription_shelf", () -> new PrescriptionShelfBlock());
	public static final RegistryObject<Block> EPOS_CASHIER_SYSTEM = REGISTRY.register("epos_cashier_system", () -> new EPOSCashierSystemBlock());
	public static final RegistryObject<Block> PRESCRIPTION_BASKET_EMPTY = REGISTRY.register("prescription_basket_empty", () -> new PrescriptionBasketEmptyBlock());
	public static final RegistryObject<Block> PRESCRIPTION_BASKET = REGISTRY.register("prescription_basket", () -> new PrescriptionBasketBlock());
	public static final RegistryObject<Block> PHARMACY_COUNTER_STOCKED = REGISTRY.register("pharmacy_counter_stocked", () -> new PharmacyCounterStockedBlock());
	public static final RegistryObject<Block> PHARMACY_COUNTERWITH_LOGO = REGISTRY.register("pharmacy_counterwith_logo", () -> new PharmacyCounterwithLogoBlock());
	public static final RegistryObject<Block> PHARMACY_COUNTER = REGISTRY.register("pharmacy_counter", () -> new PharmacyCounterBlock());
	public static final RegistryObject<Block> DECORATIVE_DIVIDE = REGISTRY.register("decorative_divide", () -> new DecorativeDivideBlock());
	public static final RegistryObject<Block> ULTRASOUND = REGISTRY.register("ultrasound", () -> new UltrasoundBlock());
	public static final RegistryObject<Block> X_RAY_LIGHT = REGISTRY.register("x_ray_light", () -> new XRayLightBlock());
	public static final RegistryObject<Block> XRAY_LIGHT_BOX_BLANK = REGISTRY.register("xray_light_box_blank", () -> new XRAYLightBoxBlankBlock());
	public static final RegistryObject<Block> XRAY_LIGHT_BOX_CHEST = REGISTRY.register("xray_light_box_chest", () -> new XRAYLightBoxChestBlock());
	public static final RegistryObject<Block> XRAY_LIGHT_BOX_FEET = REGISTRY.register("xray_light_box_feet", () -> new XRAYLightBoxFeetBlock());
	public static final RegistryObject<Block> XRAY_LIGHT_BOX_HANDS = REGISTRY.register("xray_light_box_hands", () -> new XRAYLightBoxHandsBlock());
	public static final RegistryObject<Block> XRAY_LIGHT_BOX_ARMS = REGISTRY.register("xray_light_box_arms", () -> new XRAYLightBoxArmsBlock());
	public static final RegistryObject<Block> XRAY_LIGHT_BOX_NECK = REGISTRY.register("xray_light_box_neck", () -> new XRAYLightBoxNeckBlock());
	public static final RegistryObject<Block> X_RAY_MACHINE = REGISTRY.register("x_ray_machine", () -> new XRayMachineBlock());
	public static final RegistryObject<Block> XRAY_BUCKY_STAND = REGISTRY.register("xray_bucky_stand", () -> new XRAYBuckyStandBlock());
	public static final RegistryObject<Block> COMPUTER_CT_SCAN_VIEWER = REGISTRY.register("computer_ct_scan_viewer", () -> new ComputerCTScanViewerBlock());
	public static final RegistryObject<Block> COMPUTER_X_RAY_VIEWER = REGISTRY.register("computer_x_ray_viewer", () -> new ComputerXRayViewerBlock());
	public static final RegistryObject<Block> COMPUTER_SCREEN_2_CT_SCAN_VIEWER = REGISTRY.register("computer_screen_2_ct_scan_viewer", () -> new ComputerScreen2CTScanViewerBlock());
	public static final RegistryObject<Block> COMPUTER_SCREEN_2_XRAY_VIEWER = REGISTRY.register("computer_screen_2_xray_viewer", () -> new ComputerScreen2XRAYViewerBlock());
	public static final RegistryObject<Block> BEDSIDE_HEAD_UNIT = REGISTRY.register("bedside_head_unit", () -> new BedsideHeadUnitBlock());
	public static final RegistryObject<Block> WARD_STORAGE_DRAWERS = REGISTRY.register("ward_storage_drawers", () -> new WardStorageDrawersBlock());
	public static final RegistryObject<Block> FETAL_MONITORING_WORKSTATION = REGISTRY.register("fetal_monitoring_workstation", () -> new FetalMonitoringWorkstationBlock());
	public static final RegistryObject<Block> HOSPITAL_BED = REGISTRY.register("hospital_bed", () -> new HospitalBedBlock());
	public static final RegistryObject<Block> IV_STAND = REGISTRY.register("iv_stand", () -> new IVStandBlock());
	public static final RegistryObject<Block> MEDICAL_WORKSTATION_CART = REGISTRY.register("medical_workstation_cart", () -> new MedicalWorkstationCartBlock());
	public static final RegistryObject<Block> LIFE_SUPPORT_SYRINGE_PUMPS = REGISTRY.register("life_support_syringe_pumps", () -> new LifeSupportSyringePumpsBlock());
	public static final RegistryObject<Block> HEART_RATE_MONITOR = REGISTRY.register("heart_rate_monitor", () -> new HeartRateMonitorBlock());
	public static final RegistryObject<Block> WARD_RESUS_TROLLEY = REGISTRY.register("ward_resus_trolley", () -> new WardResusTrolleyBlock());
	public static final RegistryObject<Block> MEDICAL_GAS_ALARM_PANEL = REGISTRY.register("medical_gas_alarm_panel", () -> new MedicalGasAlarmPanelBlock());
	public static final RegistryObject<Block> HAND_SANITISER_DISPENSER = REGISTRY.register("hand_sanitiser_dispenser", () -> new HandSanitiserDispenserBlock());
	public static final RegistryObject<Block> RACK_SHELVING_EMPTY = REGISTRY.register("rack_shelving_empty", () -> new RackShelvingEmptyBlock());
	public static final RegistryObject<Block> RACK_SHELVES_LINEN = REGISTRY.register("rack_shelves_linen", () -> new RackShelvesLinenBlock());
	public static final RegistryObject<Block> FIRE_EXIT_SIGN_CEILING_MOUNTED = REGISTRY.register("fire_exit_sign_ceiling_mounted", () -> new FireExitSignCeilingMountedBlock());
	public static final RegistryObject<Block> FIRE_EXIT_SIGN_WALL_MOUNTED = REGISTRY.register("fire_exit_sign_wall_mounted", () -> new FireExitSignWallMountedBlock());
	public static final RegistryObject<Block> FIRE_EXTINGUISHER = REGISTRY.register("fire_extinguisher", () -> new FireExtinguisherBlock());
	public static final RegistryObject<Block> PATIENT_INFORMAITON_POINT = REGISTRY.register("patient_informaiton_point", () -> new PatientInformaitonPointBlock());
	public static final RegistryObject<Block> ROLL_CAGE_STORAGE = REGISTRY.register("roll_cage_storage", () -> new RollCageStorageBlock());
	public static final RegistryObject<Block> SUSPENDED_CEILING = REGISTRY.register("suspended_ceiling", () -> new SuspendedCeilingBlock());
	public static final RegistryObject<Block> VINYL_FLOOR_BLUE_TYPE_1 = REGISTRY.register("vinyl_floor_blue_type_1", () -> new VinylFloorBlueType1Block());
	public static final RegistryObject<Block> VINYL_FLOOR_GREY_TYPE_1 = REGISTRY.register("vinyl_floor_grey_type_1", () -> new VinylFloorGreyType1Block());
	public static final RegistryObject<Block> VINYL_FLOOR_WHITE_TYPE_1 = REGISTRY.register("vinyl_floor_white_type_1", () -> new VinylFloorWhiteType1Block());
	public static final RegistryObject<Block> VINYL_FLOOR_LIGHT_BLUE_TYPE_1 = REGISTRY.register("vinyl_floor_light_blue_type_1", () -> new VinylFloorLightBlueType1Block());
	public static final RegistryObject<Block> VINYL_FLOOR_GREEN_TYPE_1 = REGISTRY.register("vinyl_floor_green_type_1", () -> new VinylFloorGreenType1Block());
	public static final RegistryObject<Block> VINYL_FLOOR_AQUA_TYPE_1 = REGISTRY.register("vinyl_floor_aqua_type_1", () -> new VinylFloorAquaType1Block());
	public static final RegistryObject<Block> VINYL_FLOOR_RED_TYPE_1 = REGISTRY.register("vinyl_floor_red_type_1", () -> new VinylFloorRedType1Block());
	public static final RegistryObject<Block> VINYL_WALL_BLUE_TYPE_1 = REGISTRY.register("vinyl_wall_blue_type_1", () -> new VinylWallBlueType1Block());
	public static final RegistryObject<Block> VINYL_WALL_GREY_TYPE_1 = REGISTRY.register("vinyl_wall_grey_type_1", () -> new VinylWallGreyType1Block());
	public static final RegistryObject<Block> VINYL_WALL_WHITE_TYPE_1 = REGISTRY.register("vinyl_wall_white_type_1", () -> new VinylWallWhiteType1Block());
	public static final RegistryObject<Block> VINYL_WALL_LIGHT_BLUE_TYPE_1 = REGISTRY.register("vinyl_wall_light_blue_type_1", () -> new VinylWallLightBlueType1Block());
	public static final RegistryObject<Block> VINYL_WALL_GREEN_TYPE_1 = REGISTRY.register("vinyl_wall_green_type_1", () -> new VinylWallGreenType1Block());
	public static final RegistryObject<Block> VINYL_WALL_AQUA_TYPE_1 = REGISTRY.register("vinyl_wall_aqua_type_1", () -> new VinylWallAquaType1Block());
	public static final RegistryObject<Block> VINYL_WALL_RED_TYPE_1 = REGISTRY.register("vinyl_wall_red_type_1", () -> new VinylWallRedType1Block());
	public static final RegistryObject<Block> VINYL_FLOOR_BLUE_TYPE_2 = REGISTRY.register("vinyl_floor_blue_type_2", () -> new VinylFloorBlueType2Block());
	public static final RegistryObject<Block> VINYL_FLOOR_BEIGE_TYPE_2 = REGISTRY.register("vinyl_floor_beige_type_2", () -> new VinylFloorBeigeType2Block());
	public static final RegistryObject<Block> VINYL_FLOOR_GREY_TYPE_2 = REGISTRY.register("vinyl_floor_grey_type_2", () -> new VinylFloorGreyType2Block());
	public static final RegistryObject<Block> VINYL_FLOOR_AQUA_TYPE_2 = REGISTRY.register("vinyl_floor_aqua_type_2", () -> new VinylFloorAquaType2Block());
	public static final RegistryObject<Block> VINYL_FLOOR_SALMON_TYPE_2 = REGISTRY.register("vinyl_floor_salmon_type_2", () -> new VinylFloorSalmonType2Block());
	public static final RegistryObject<Block> VINYL_WALL_BLUE_TYPE_2 = REGISTRY.register("vinyl_wall_blue_type_2", () -> new VinylWallBlueType2Block());
	public static final RegistryObject<Block> VINYL_WALL_BEIGE_TYPE_2 = REGISTRY.register("vinyl_wall_beige_type_2", () -> new VinylWallBeigeType2Block());
	public static final RegistryObject<Block> VINYL_WALL_GREY_TYPE_2 = REGISTRY.register("vinyl_wall_grey_type_2", () -> new VinylWallGreyType2Block());
	public static final RegistryObject<Block> VINYL_WALL_AQUA_TYPE_2 = REGISTRY.register("vinyl_wall_aqua_type_2", () -> new VinylWallAquaType2Block());
	public static final RegistryObject<Block> VINYL_WALL_SALMON_TYPE_2 = REGISTRY.register("vinyl_wall_salmon_type_2", () -> new VinylWallSalmonType2Block());
	public static final RegistryObject<Block> BRICK_BEIGE = REGISTRY.register("brick_beige", () -> new BrickBeigeBlock());
	public static final RegistryObject<Block> BRICK_GREY = REGISTRY.register("brick_grey", () -> new BrickGreyBlock());
	public static final RegistryObject<Block> BRICK_DARK = REGISTRY.register("brick_dark", () -> new BrickDarkBlock());
	public static final RegistryObject<Block> BRICK_RED = REGISTRY.register("brick_red", () -> new BrickRedBlock());
	public static final RegistryObject<Block> SMOOTH_CONCRETE = REGISTRY.register("smooth_concrete", () -> new SmoothConcreteBlock());
	public static final RegistryObject<Block> PLASTERED_WALL_BEIGE = REGISTRY.register("plastered_wall_beige", () -> new PlasteredWallBeigeBlock());
	public static final RegistryObject<Block> PLASTERED_WALL_BLUE = REGISTRY.register("plastered_wall_blue", () -> new PlasteredWallBlueBlock());
	public static final RegistryObject<Block> PLASTERED_WALL_GREEN = REGISTRY.register("plastered_wall_green", () -> new PlasteredWallGreenBlock());
	public static final RegistryObject<Block> PLASTERED_WALL_GREY = REGISTRY.register("plastered_wall_grey", () -> new PlasteredWallGreyBlock());
	public static final RegistryObject<Block> PLASTERED_WALL_LIME = REGISTRY.register("plastered_wall_lime", () -> new PlasteredWallLimeBlock());
	public static final RegistryObject<Block> PLASTERED_WALL_SKY_BLUE = REGISTRY.register("plastered_wall_sky_blue", () -> new PlasteredWallSkyBlueBlock());
	public static final RegistryObject<Block> PLASTERED_WALL_WHITE = REGISTRY.register("plastered_wall_white", () -> new PlasteredWallWhiteBlock());
	public static final RegistryObject<Block> VENTILATION = REGISTRY.register("ventilation", () -> new VentilationBlock());
	public static final RegistryObject<Block> CARDBOARD_BOX = REGISTRY.register("cardboard_box", () -> new CardboardBoxBlock());
	public static final RegistryObject<Block> VINYL_FLOOR_GREY = REGISTRY.register("vinyl_floor_grey", () -> new VinylFloorGreyBlock());
	public static final RegistryObject<Block> CLADDING_STONE_EFFECT = REGISTRY.register("cladding_stone_effect", () -> new CladdingStoneEffectBlock());
	public static final RegistryObject<Block> BLUE_DESK_TRAY = REGISTRY.register("blue_desk_tray", () -> new BlueDeskTrayBlock());
	public static final RegistryObject<Block> RED_DESK_TRAY = REGISTRY.register("red_desk_tray", () -> new RedDeskTrayBlock());
	public static final RegistryObject<Block> DRINKS_FRIDGE = REGISTRY.register("drinks_fridge", () -> new DrinksFridgeBlock());
	public static final RegistryObject<Block> CLEANING_TROLLEY = REGISTRY.register("cleaning_trolley", () -> new CleaningTrolleyBlock());
	public static final RegistryObject<Block> WET_FLOOR_SIGN = REGISTRY.register("wet_floor_sign", () -> new WetFloorSignBlock());
	public static final RegistryObject<Block> OFFICE_WALL_PHONE = REGISTRY.register("office_wall_phone", () -> new OfficeWallPhoneBlock());
	public static final RegistryObject<Block> OFFICE_DESK_PHONE = REGISTRY.register("office_desk_phone", () -> new OfficeDeskPhoneBlock());
	public static final RegistryObject<Block> OFFICE_PRINTER = REGISTRY.register("office_printer", () -> new OfficePrinterBlock());
	public static final RegistryObject<Block> OFFICE_DESK = REGISTRY.register("office_desk", () -> new OfficeDeskBlock());
	public static final RegistryObject<Block> OFFICE_DESK_WITH_BACK = REGISTRY.register("office_desk_with_back", () -> new OfficeDeskWithBackBlock());
	public static final RegistryObject<Block> WASTE_BIN_DOMESTIC_WASTE = REGISTRY.register("waste_bin_domestic_waste", () -> new WasteBinDomesticWasteBlock());
	public static final RegistryObject<Block> WASTE_BIN_CLINICAL_WASTE = REGISTRY.register("waste_bin_clinical_waste", () -> new WasteBinClinicalWasteBlock());
	public static final RegistryObject<Block> LIGHT_BLOCK = REGISTRY.register("light_block", () -> new LightBlockBlock());
	public static final RegistryObject<Block> BLOCK_OF_STAINLESS_STEEL = REGISTRY.register("block_of_stainless_steel", () -> new BlockOfStainlessSteelBlock());
	public static final RegistryObject<Block> WARNING = REGISTRY.register("warning", () -> new WarningBlock());
	public static final RegistryObject<Block> BLOOD_CENTRIFUGE = REGISTRY.register("blood_centrifuge", () -> new BloodCentrifugeBlock());
	public static final RegistryObject<Block> MIXED_BLOOD = REGISTRY.register("mixed_blood", () -> new MixedBloodBlock());
	public static final RegistryObject<Block> MINI_TILES = REGISTRY.register("mini_tiles", () -> new MiniTilesBlock());
	public static final RegistryObject<Block> LARGEDARKTILES = REGISTRY.register("largedarktiles", () -> new LargedarktilesBlock());
	public static final RegistryObject<Block> LARGELIGHTBLUETILES = REGISTRY.register("largelightbluetiles", () -> new LargelightbluetilesBlock());
	public static final RegistryObject<Block> LABTILES_1 = REGISTRY.register("labtiles_1", () -> new Labtiles1Block());
	public static final RegistryObject<Block> LABTILES_2 = REGISTRY.register("labtiles_2", () -> new Labtiles2Block());
	public static final RegistryObject<Block> LABTILES_3 = REGISTRY.register("labtiles_3", () -> new Labtiles3Block());
	public static final RegistryObject<Block> LABTILES_4 = REGISTRY.register("labtiles_4", () -> new Labtiles4Block());
	public static final RegistryObject<Block> DARKLABTILES_1 = REGISTRY.register("darklabtiles_1", () -> new Darklabtiles1Block());
	public static final RegistryObject<Block> DARKLABTILES_2 = REGISTRY.register("darklabtiles_2", () -> new Darklabtiles2Block());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}