/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.derpymeow.hospitals.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.derpymeow.hospitals.item.UnprocessedSteelItem;
import net.derpymeow.hospitals.item.SyringebloodOnegativeItem;
import net.derpymeow.hospitals.item.SyringeBloodOPositiveItem;
import net.derpymeow.hospitals.item.SyringeBloodMixedItem;
import net.derpymeow.hospitals.item.SyringeBloodBPositiveItem;
import net.derpymeow.hospitals.item.SyringeBloodBNegativeItem;
import net.derpymeow.hospitals.item.SyringeBloodAPositiveItem;
import net.derpymeow.hospitals.item.SyringeBloodANegativeItem;
import net.derpymeow.hospitals.item.SyringeBloodABPositiveItem;
import net.derpymeow.hospitals.item.SyringeBloodABNegativeItem;
import net.derpymeow.hospitals.item.StainlessSteelItem;
import net.derpymeow.hospitals.item.SmallMedkitItem;
import net.derpymeow.hospitals.item.ScrubsItem;
import net.derpymeow.hospitals.item.ScrubmaskItem;
import net.derpymeow.hospitals.item.PillbottleemptyItem;
import net.derpymeow.hospitals.item.Pillbottle9Item;
import net.derpymeow.hospitals.item.Pillbottle7Item;
import net.derpymeow.hospitals.item.Pillbottle6Item;
import net.derpymeow.hospitals.item.Pillbottle4Item;
import net.derpymeow.hospitals.item.Pillbottle3Item;
import net.derpymeow.hospitals.item.Pillbottle2Item;
import net.derpymeow.hospitals.item.Pillbottle21Item;
import net.derpymeow.hospitals.item.Pillbottle20Item;
import net.derpymeow.hospitals.item.Pillbottle1Item;
import net.derpymeow.hospitals.item.Pillbottle12Item;
import net.derpymeow.hospitals.item.Pillbottle11Item;
import net.derpymeow.hospitals.item.Pillbottle0Item;
import net.derpymeow.hospitals.item.PillItem;
import net.derpymeow.hospitals.item.PillBottle8Item;
import net.derpymeow.hospitals.item.PillBottle5Item;
import net.derpymeow.hospitals.item.PillBottle43Item;
import net.derpymeow.hospitals.item.PillBottle42Item;
import net.derpymeow.hospitals.item.PillBottle41Item;
import net.derpymeow.hospitals.item.PillBottle40Item;
import net.derpymeow.hospitals.item.PillBottle39Item;
import net.derpymeow.hospitals.item.PillBottle38Item;
import net.derpymeow.hospitals.item.PillBottle37Item;
import net.derpymeow.hospitals.item.PillBottle36Item;
import net.derpymeow.hospitals.item.PillBottle35Item;
import net.derpymeow.hospitals.item.PillBottle34Item;
import net.derpymeow.hospitals.item.PillBottle33Item;
import net.derpymeow.hospitals.item.PillBottle32Item;
import net.derpymeow.hospitals.item.PillBottle31Item;
import net.derpymeow.hospitals.item.PillBottle30Item;
import net.derpymeow.hospitals.item.PillBottle29Item;
import net.derpymeow.hospitals.item.PillBottle28Item;
import net.derpymeow.hospitals.item.PillBottle27Item;
import net.derpymeow.hospitals.item.PillBottle26Item;
import net.derpymeow.hospitals.item.PillBottle25Item;
import net.derpymeow.hospitals.item.PillBottle24Item;
import net.derpymeow.hospitals.item.PillBottle23Item;
import net.derpymeow.hospitals.item.PillBottle22Item;
import net.derpymeow.hospitals.item.PillBottle19Item;
import net.derpymeow.hospitals.item.PillBottle18Item;
import net.derpymeow.hospitals.item.PillBottle17Item;
import net.derpymeow.hospitals.item.PillBottle16Item;
import net.derpymeow.hospitals.item.PillBottle15Item;
import net.derpymeow.hospitals.item.PillBottle14Item;
import net.derpymeow.hospitals.item.PillBottle13Item;
import net.derpymeow.hospitals.item.PillBottle10Item;
import net.derpymeow.hospitals.item.Pill9Item;
import net.derpymeow.hospitals.item.Pill8Item;
import net.derpymeow.hospitals.item.Pill7Item;
import net.derpymeow.hospitals.item.Pill6Item;
import net.derpymeow.hospitals.item.Pill5Item;
import net.derpymeow.hospitals.item.Pill4Item;
import net.derpymeow.hospitals.item.Pill43Item;
import net.derpymeow.hospitals.item.Pill42Item;
import net.derpymeow.hospitals.item.Pill41Item;
import net.derpymeow.hospitals.item.Pill40Item;
import net.derpymeow.hospitals.item.Pill3Item;
import net.derpymeow.hospitals.item.Pill39Item;
import net.derpymeow.hospitals.item.Pill38Item;
import net.derpymeow.hospitals.item.Pill37Item;
import net.derpymeow.hospitals.item.Pill36Item;
import net.derpymeow.hospitals.item.Pill35Item;
import net.derpymeow.hospitals.item.Pill34Item;
import net.derpymeow.hospitals.item.Pill33Item;
import net.derpymeow.hospitals.item.Pill32Item;
import net.derpymeow.hospitals.item.Pill31Item;
import net.derpymeow.hospitals.item.Pill30Item;
import net.derpymeow.hospitals.item.Pill2Item;
import net.derpymeow.hospitals.item.Pill29Item;
import net.derpymeow.hospitals.item.Pill28Item;
import net.derpymeow.hospitals.item.Pill27Item;
import net.derpymeow.hospitals.item.Pill26Item;
import net.derpymeow.hospitals.item.Pill25Item;
import net.derpymeow.hospitals.item.Pill24Item;
import net.derpymeow.hospitals.item.Pill23Item;
import net.derpymeow.hospitals.item.Pill22Item;
import net.derpymeow.hospitals.item.Pill21Item;
import net.derpymeow.hospitals.item.Pill20Item;
import net.derpymeow.hospitals.item.Pill1Item;
import net.derpymeow.hospitals.item.Pill19Item;
import net.derpymeow.hospitals.item.Pill18Item;
import net.derpymeow.hospitals.item.Pill17Item;
import net.derpymeow.hospitals.item.Pill16Item;
import net.derpymeow.hospitals.item.Pill15Item;
import net.derpymeow.hospitals.item.Pill14Item;
import net.derpymeow.hospitals.item.Pill13Item;
import net.derpymeow.hospitals.item.Pill12Item;
import net.derpymeow.hospitals.item.Pill11Item;
import net.derpymeow.hospitals.item.Pill10Item;
import net.derpymeow.hospitals.item.LargemedkitItem;
import net.derpymeow.hospitals.item.EmptySyringeItem;
import net.derpymeow.hospitals.item.CreativePillItem;
import net.derpymeow.hospitals.item.ComputerItem;
import net.derpymeow.hospitals.item.ComputerChipItem;
import net.derpymeow.hospitals.item.BloodbagopositiveItem;
import net.derpymeow.hospitals.item.BloodbagonegativeItem;
import net.derpymeow.hospitals.item.BloodbagemptyItem;
import net.derpymeow.hospitals.item.BloodbagbpositiveItem;
import net.derpymeow.hospitals.item.BloodbagbnegativeItem;
import net.derpymeow.hospitals.item.BloodbagapositiveItem;
import net.derpymeow.hospitals.item.BloodbaganegativeItem;
import net.derpymeow.hospitals.item.BloodbagabpositiveItem;
import net.derpymeow.hospitals.item.BloodbagabnegativeItem;
import net.derpymeow.hospitals.HospitalsMod;

public class HospitalsModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, HospitalsMod.MODID);
	public static final RegistryObject<Item> TH_BLOCK = block(HospitalsModBlocks.TH_BLOCK);
	public static final RegistryObject<Item> PH_BLOCK = block(HospitalsModBlocks.PH_BLOCK);
	public static final RegistryObject<Item> RA_BLOCK = block(HospitalsModBlocks.RA_BLOCK);
	public static final RegistryObject<Item> WA_BLOCK = block(HospitalsModBlocks.WA_BLOCK);
	public static final RegistryObject<Item> FA_BLOCK = block(HospitalsModBlocks.FA_BLOCK);
	public static final RegistryObject<Item> MEDICAL_CROSS = block(HospitalsModBlocks.MEDICAL_CROSS);
	public static final RegistryObject<Item> ANAESTHETIC_MACHINE = block(HospitalsModBlocks.ANAESTHETIC_MACHINE);
	public static final RegistryObject<Item> SURGICAL_REFRIDGERATED_CABINET = block(HospitalsModBlocks.SURGICAL_REFRIDGERATED_CABINET);
	public static final RegistryObject<Item> SURGICAL_WORKTOP_TABLE = block(HospitalsModBlocks.SURGICAL_WORKTOP_TABLE);
	public static final RegistryObject<Item> SURGICAL_INSTRUMENT_TROLLEY = block(HospitalsModBlocks.SURGICAL_INSTRUMENT_TROLLEY);
	public static final RegistryObject<Item> OPERATING_TABLE = block(HospitalsModBlocks.OPERATING_TABLE);
	public static final RegistryObject<Item> SCRUB_SINK = block(HospitalsModBlocks.SCRUB_SINK);
	public static final RegistryObject<Item> WALL_STORAGE_TUBS_RED = block(HospitalsModBlocks.WALL_STORAGE_TUBS_RED);
	public static final RegistryObject<Item> WALL_STORAGE_TUBS_YELLOW = block(HospitalsModBlocks.WALL_STORAGE_TUBS_YELLOW);
	public static final RegistryObject<Item> SURGICAL_LAMP = block(HospitalsModBlocks.SURGICAL_LAMP);
	public static final RegistryObject<Item> SURGICAL_TROLLEY = block(HospitalsModBlocks.SURGICAL_TROLLEY);
	public static final RegistryObject<Item> STERILE_WORKTOP = block(HospitalsModBlocks.STERILE_WORKTOP);
	public static final RegistryObject<Item> STERILE_WORK_COUNTER_WITH_SHELF = block(HospitalsModBlocks.STERILE_WORK_COUNTER_WITH_SHELF);
	public static final RegistryObject<Item> SURGICAL_WORKSTATION = block(HospitalsModBlocks.SURGICAL_WORKSTATION);
	public static final RegistryObject<Item> OPERATING_ROOM_CONTROL_PANEL = block(HospitalsModBlocks.OPERATING_ROOM_CONTROL_PANEL);
	public static final RegistryObject<Item> SURGICAL_INSTRUMENTS = block(HospitalsModBlocks.SURGICAL_INSTRUMENTS);
	public static final RegistryObject<Item> MEDICAL_GAS_CEILING_MOUNTED = block(HospitalsModBlocks.MEDICAL_GAS_CEILING_MOUNTED);
	public static final RegistryObject<Item> ILLUMINATED_PHARMACY_SIGN = block(HospitalsModBlocks.ILLUMINATED_PHARMACY_SIGN);
	public static final RegistryObject<Item> STORE_SHELF_EMPTY = block(HospitalsModBlocks.STORE_SHELF_EMPTY);
	public static final RegistryObject<Item> STORE_SHELF_STOCKED = block(HospitalsModBlocks.STORE_SHELF_STOCKED);
	public static final RegistryObject<Item> COMPOUNDING_ISOLATOR = block(HospitalsModBlocks.COMPOUNDING_ISOLATOR);
	public static final RegistryObject<Item> ANALYTICAL_BALANCE = block(HospitalsModBlocks.ANALYTICAL_BALANCE);
	public static final RegistryObject<Item> REFRIDGERATED_CENTRIFUGE = block(HospitalsModBlocks.REFRIDGERATED_CENTRIFUGE);
	public static final RegistryObject<Item> WORKTOP_WITH_SHELF = block(HospitalsModBlocks.WORKTOP_WITH_SHELF);
	public static final RegistryObject<Item> WORKTOP = block(HospitalsModBlocks.WORKTOP);
	public static final RegistryObject<Item> LABORATORY_FRIDGE = block(HospitalsModBlocks.LABORATORY_FRIDGE);
	public static final RegistryObject<Item> CAPSULE_FILLING_MACHINE = block(HospitalsModBlocks.CAPSULE_FILLING_MACHINE);
	public static final RegistryObject<Item> BOTTLE_FILLING_MACHINE = block(HospitalsModBlocks.BOTTLE_FILLING_MACHINE);
	public static final RegistryObject<Item> MEDICATION_DRAWERS = block(HospitalsModBlocks.MEDICATION_DRAWERS);
	public static final RegistryObject<Item> PRESCRIPTION_SHELF = block(HospitalsModBlocks.PRESCRIPTION_SHELF);
	public static final RegistryObject<Item> EPOS_CASHIER_SYSTEM = block(HospitalsModBlocks.EPOS_CASHIER_SYSTEM);
	public static final RegistryObject<Item> PRESCRIPTION_BASKET_EMPTY = block(HospitalsModBlocks.PRESCRIPTION_BASKET_EMPTY);
	public static final RegistryObject<Item> PRESCRIPTION_BASKET = block(HospitalsModBlocks.PRESCRIPTION_BASKET);
	public static final RegistryObject<Item> PHARMACY_COUNTER_STOCKED = block(HospitalsModBlocks.PHARMACY_COUNTER_STOCKED);
	public static final RegistryObject<Item> PHARMACY_COUNTERWITH_LOGO = block(HospitalsModBlocks.PHARMACY_COUNTERWITH_LOGO);
	public static final RegistryObject<Item> PHARMACY_COUNTER = block(HospitalsModBlocks.PHARMACY_COUNTER);
	public static final RegistryObject<Item> DECORATIVE_DIVIDE = block(HospitalsModBlocks.DECORATIVE_DIVIDE);
	public static final RegistryObject<Item> ULTRASOUND = block(HospitalsModBlocks.ULTRASOUND);
	public static final RegistryObject<Item> X_RAY_LIGHT = block(HospitalsModBlocks.X_RAY_LIGHT);
	public static final RegistryObject<Item> XRAY_LIGHT_BOX_BLANK = block(HospitalsModBlocks.XRAY_LIGHT_BOX_BLANK);
	public static final RegistryObject<Item> XRAY_LIGHT_BOX_CHEST = block(HospitalsModBlocks.XRAY_LIGHT_BOX_CHEST);
	public static final RegistryObject<Item> XRAY_LIGHT_BOX_FEET = block(HospitalsModBlocks.XRAY_LIGHT_BOX_FEET);
	public static final RegistryObject<Item> XRAY_LIGHT_BOX_HANDS = block(HospitalsModBlocks.XRAY_LIGHT_BOX_HANDS);
	public static final RegistryObject<Item> XRAY_LIGHT_BOX_ARMS = block(HospitalsModBlocks.XRAY_LIGHT_BOX_ARMS);
	public static final RegistryObject<Item> XRAY_LIGHT_BOX_NECK = block(HospitalsModBlocks.XRAY_LIGHT_BOX_NECK);
	public static final RegistryObject<Item> X_RAY_MACHINE = block(HospitalsModBlocks.X_RAY_MACHINE);
	public static final RegistryObject<Item> XRAY_BUCKY_STAND = block(HospitalsModBlocks.XRAY_BUCKY_STAND);
	public static final RegistryObject<Item> COMPUTER_CT_SCAN_VIEWER = block(HospitalsModBlocks.COMPUTER_CT_SCAN_VIEWER);
	public static final RegistryObject<Item> COMPUTER_X_RAY_VIEWER = block(HospitalsModBlocks.COMPUTER_X_RAY_VIEWER);
	public static final RegistryObject<Item> COMPUTER_SCREEN_2_CT_SCAN_VIEWER = block(HospitalsModBlocks.COMPUTER_SCREEN_2_CT_SCAN_VIEWER);
	public static final RegistryObject<Item> COMPUTER_SCREEN_2_XRAY_VIEWER = block(HospitalsModBlocks.COMPUTER_SCREEN_2_XRAY_VIEWER);
	public static final RegistryObject<Item> BEDSIDE_HEAD_UNIT = block(HospitalsModBlocks.BEDSIDE_HEAD_UNIT);
	public static final RegistryObject<Item> WARD_STORAGE_DRAWERS = block(HospitalsModBlocks.WARD_STORAGE_DRAWERS);
	public static final RegistryObject<Item> FETAL_MONITORING_WORKSTATION = block(HospitalsModBlocks.FETAL_MONITORING_WORKSTATION);
	public static final RegistryObject<Item> HOSPITAL_BED = block(HospitalsModBlocks.HOSPITAL_BED);
	public static final RegistryObject<Item> IV_STAND = block(HospitalsModBlocks.IV_STAND);
	public static final RegistryObject<Item> MEDICAL_WORKSTATION_CART = block(HospitalsModBlocks.MEDICAL_WORKSTATION_CART);
	public static final RegistryObject<Item> LIFE_SUPPORT_SYRINGE_PUMPS = block(HospitalsModBlocks.LIFE_SUPPORT_SYRINGE_PUMPS);
	public static final RegistryObject<Item> HEART_RATE_MONITOR = block(HospitalsModBlocks.HEART_RATE_MONITOR);
	public static final RegistryObject<Item> WARD_RESUS_TROLLEY = block(HospitalsModBlocks.WARD_RESUS_TROLLEY);
	public static final RegistryObject<Item> MEDICAL_GAS_ALARM_PANEL = block(HospitalsModBlocks.MEDICAL_GAS_ALARM_PANEL);
	public static final RegistryObject<Item> HAND_SANITISER_DISPENSER = block(HospitalsModBlocks.HAND_SANITISER_DISPENSER);
	public static final RegistryObject<Item> RACK_SHELVING_EMPTY = block(HospitalsModBlocks.RACK_SHELVING_EMPTY);
	public static final RegistryObject<Item> RACK_SHELVES_LINEN = block(HospitalsModBlocks.RACK_SHELVES_LINEN);
	public static final RegistryObject<Item> FIRE_EXIT_SIGN_CEILING_MOUNTED = block(HospitalsModBlocks.FIRE_EXIT_SIGN_CEILING_MOUNTED);
	public static final RegistryObject<Item> FIRE_EXIT_SIGN_WALL_MOUNTED = block(HospitalsModBlocks.FIRE_EXIT_SIGN_WALL_MOUNTED);
	public static final RegistryObject<Item> FIRE_EXTINGUISHER = block(HospitalsModBlocks.FIRE_EXTINGUISHER);
	public static final RegistryObject<Item> PATIENT_INFORMAITON_POINT = block(HospitalsModBlocks.PATIENT_INFORMAITON_POINT);
	public static final RegistryObject<Item> ROLL_CAGE_STORAGE = block(HospitalsModBlocks.ROLL_CAGE_STORAGE);
	public static final RegistryObject<Item> SUSPENDED_CEILING = block(HospitalsModBlocks.SUSPENDED_CEILING);
	public static final RegistryObject<Item> VINYL_FLOOR_BLUE_TYPE_1 = block(HospitalsModBlocks.VINYL_FLOOR_BLUE_TYPE_1);
	public static final RegistryObject<Item> VINYL_FLOOR_GREY_TYPE_1 = block(HospitalsModBlocks.VINYL_FLOOR_GREY_TYPE_1);
	public static final RegistryObject<Item> VINYL_FLOOR_WHITE_TYPE_1 = block(HospitalsModBlocks.VINYL_FLOOR_WHITE_TYPE_1);
	public static final RegistryObject<Item> VINYL_FLOOR_LIGHT_BLUE_TYPE_1 = block(HospitalsModBlocks.VINYL_FLOOR_LIGHT_BLUE_TYPE_1);
	public static final RegistryObject<Item> VINYL_FLOOR_GREEN_TYPE_1 = block(HospitalsModBlocks.VINYL_FLOOR_GREEN_TYPE_1);
	public static final RegistryObject<Item> VINYL_FLOOR_AQUA_TYPE_1 = block(HospitalsModBlocks.VINYL_FLOOR_AQUA_TYPE_1);
	public static final RegistryObject<Item> VINYL_FLOOR_RED_TYPE_1 = block(HospitalsModBlocks.VINYL_FLOOR_RED_TYPE_1);
	public static final RegistryObject<Item> VINYL_WALL_BLUE_TYPE_1 = block(HospitalsModBlocks.VINYL_WALL_BLUE_TYPE_1);
	public static final RegistryObject<Item> VINYL_WALL_GREY_TYPE_1 = block(HospitalsModBlocks.VINYL_WALL_GREY_TYPE_1);
	public static final RegistryObject<Item> VINYL_WALL_WHITE_TYPE_1 = block(HospitalsModBlocks.VINYL_WALL_WHITE_TYPE_1);
	public static final RegistryObject<Item> VINYL_WALL_LIGHT_BLUE_TYPE_1 = block(HospitalsModBlocks.VINYL_WALL_LIGHT_BLUE_TYPE_1);
	public static final RegistryObject<Item> VINYL_WALL_GREEN_TYPE_1 = block(HospitalsModBlocks.VINYL_WALL_GREEN_TYPE_1);
	public static final RegistryObject<Item> VINYL_WALL_AQUA_TYPE_1 = block(HospitalsModBlocks.VINYL_WALL_AQUA_TYPE_1);
	public static final RegistryObject<Item> VINYL_WALL_RED_TYPE_1 = block(HospitalsModBlocks.VINYL_WALL_RED_TYPE_1);
	public static final RegistryObject<Item> VINYL_FLOOR_BLUE_TYPE_2 = block(HospitalsModBlocks.VINYL_FLOOR_BLUE_TYPE_2);
	public static final RegistryObject<Item> VINYL_FLOOR_BEIGE_TYPE_2 = block(HospitalsModBlocks.VINYL_FLOOR_BEIGE_TYPE_2);
	public static final RegistryObject<Item> VINYL_FLOOR_GREY_TYPE_2 = block(HospitalsModBlocks.VINYL_FLOOR_GREY_TYPE_2);
	public static final RegistryObject<Item> VINYL_FLOOR_AQUA_TYPE_2 = block(HospitalsModBlocks.VINYL_FLOOR_AQUA_TYPE_2);
	public static final RegistryObject<Item> VINYL_FLOOR_SALMON_TYPE_2 = block(HospitalsModBlocks.VINYL_FLOOR_SALMON_TYPE_2);
	public static final RegistryObject<Item> VINYL_WALL_BLUE_TYPE_2 = block(HospitalsModBlocks.VINYL_WALL_BLUE_TYPE_2);
	public static final RegistryObject<Item> VINYL_WALL_BEIGE_TYPE_2 = block(HospitalsModBlocks.VINYL_WALL_BEIGE_TYPE_2);
	public static final RegistryObject<Item> VINYL_WALL_GREY_TYPE_2 = block(HospitalsModBlocks.VINYL_WALL_GREY_TYPE_2);
	public static final RegistryObject<Item> VINYL_WALL_AQUA_TYPE_2 = block(HospitalsModBlocks.VINYL_WALL_AQUA_TYPE_2);
	public static final RegistryObject<Item> VINYL_WALL_SALMON_TYPE_2 = block(HospitalsModBlocks.VINYL_WALL_SALMON_TYPE_2);
	public static final RegistryObject<Item> BRICK_BEIGE = block(HospitalsModBlocks.BRICK_BEIGE);
	public static final RegistryObject<Item> BRICK_GREY = block(HospitalsModBlocks.BRICK_GREY);
	public static final RegistryObject<Item> BRICK_DARK = block(HospitalsModBlocks.BRICK_DARK);
	public static final RegistryObject<Item> BRICK_RED = block(HospitalsModBlocks.BRICK_RED);
	public static final RegistryObject<Item> SMOOTH_CONCRETE = block(HospitalsModBlocks.SMOOTH_CONCRETE);
	public static final RegistryObject<Item> PLASTERED_WALL_BEIGE = block(HospitalsModBlocks.PLASTERED_WALL_BEIGE);
	public static final RegistryObject<Item> PLASTERED_WALL_BLUE = block(HospitalsModBlocks.PLASTERED_WALL_BLUE);
	public static final RegistryObject<Item> PLASTERED_WALL_GREEN = block(HospitalsModBlocks.PLASTERED_WALL_GREEN);
	public static final RegistryObject<Item> PLASTERED_WALL_GREY = block(HospitalsModBlocks.PLASTERED_WALL_GREY);
	public static final RegistryObject<Item> PLASTERED_WALL_LIME = block(HospitalsModBlocks.PLASTERED_WALL_LIME);
	public static final RegistryObject<Item> PLASTERED_WALL_SKY_BLUE = block(HospitalsModBlocks.PLASTERED_WALL_SKY_BLUE);
	public static final RegistryObject<Item> PLASTERED_WALL_WHITE = block(HospitalsModBlocks.PLASTERED_WALL_WHITE);
	public static final RegistryObject<Item> VENTILATION = block(HospitalsModBlocks.VENTILATION);
	public static final RegistryObject<Item> CARDBOARD_BOX = block(HospitalsModBlocks.CARDBOARD_BOX);
	public static final RegistryObject<Item> VINYL_FLOOR_GREY = block(HospitalsModBlocks.VINYL_FLOOR_GREY);
	public static final RegistryObject<Item> CLADDING_STONE_EFFECT = block(HospitalsModBlocks.CLADDING_STONE_EFFECT);
	public static final RegistryObject<Item> BLUE_DESK_TRAY = block(HospitalsModBlocks.BLUE_DESK_TRAY);
	public static final RegistryObject<Item> RED_DESK_TRAY = block(HospitalsModBlocks.RED_DESK_TRAY);
	public static final RegistryObject<Item> DRINKS_FRIDGE = block(HospitalsModBlocks.DRINKS_FRIDGE);
	public static final RegistryObject<Item> CLEANING_TROLLEY = block(HospitalsModBlocks.CLEANING_TROLLEY);
	public static final RegistryObject<Item> WET_FLOOR_SIGN = block(HospitalsModBlocks.WET_FLOOR_SIGN);
	public static final RegistryObject<Item> OFFICE_WALL_PHONE = block(HospitalsModBlocks.OFFICE_WALL_PHONE);
	public static final RegistryObject<Item> OFFICE_DESK_PHONE = block(HospitalsModBlocks.OFFICE_DESK_PHONE);
	public static final RegistryObject<Item> OFFICE_PRINTER = block(HospitalsModBlocks.OFFICE_PRINTER);
	public static final RegistryObject<Item> OFFICE_DESK = block(HospitalsModBlocks.OFFICE_DESK);
	public static final RegistryObject<Item> OFFICE_DESK_WITH_BACK = block(HospitalsModBlocks.OFFICE_DESK_WITH_BACK);
	public static final RegistryObject<Item> WASTE_BIN_DOMESTIC_WASTE = block(HospitalsModBlocks.WASTE_BIN_DOMESTIC_WASTE);
	public static final RegistryObject<Item> WASTE_BIN_CLINICAL_WASTE = block(HospitalsModBlocks.WASTE_BIN_CLINICAL_WASTE);
	public static final RegistryObject<Item> PILL = REGISTRY.register("pill", () -> new PillItem());
	public static final RegistryObject<Item> SCRUBS_HELMET = REGISTRY.register("scrubs_helmet", () -> new ScrubsItem.Helmet());
	public static final RegistryObject<Item> SCRUBS_CHESTPLATE = REGISTRY.register("scrubs_chestplate", () -> new ScrubsItem.Chestplate());
	public static final RegistryObject<Item> SCRUBS_LEGGINGS = REGISTRY.register("scrubs_leggings", () -> new ScrubsItem.Leggings());
	public static final RegistryObject<Item> SCRUBS_BOOTS = REGISTRY.register("scrubs_boots", () -> new ScrubsItem.Boots());
	public static final RegistryObject<Item> NURSE_SPAWN_EGG = REGISTRY.register("nurse_spawn_egg", () -> new ForgeSpawnEggItem(HospitalsModEntities.NURSE, -1, -39220, new Item.Properties()));
	public static final RegistryObject<Item> DOCTOR_SPAWN_EGG = REGISTRY.register("doctor_spawn_egg", () -> new ForgeSpawnEggItem(HospitalsModEntities.DOCTOR, -1, -52429, new Item.Properties()));
	public static final RegistryObject<Item> PILL_1 = REGISTRY.register("pill_1", () -> new Pill1Item());
	public static final RegistryObject<Item> PILL_2 = REGISTRY.register("pill_2", () -> new Pill2Item());
	public static final RegistryObject<Item> PILL_3 = REGISTRY.register("pill_3", () -> new Pill3Item());
	public static final RegistryObject<Item> PILL_4 = REGISTRY.register("pill_4", () -> new Pill4Item());
	public static final RegistryObject<Item> PILL_5 = REGISTRY.register("pill_5", () -> new Pill5Item());
	public static final RegistryObject<Item> PILL_6 = REGISTRY.register("pill_6", () -> new Pill6Item());
	public static final RegistryObject<Item> PILL_7 = REGISTRY.register("pill_7", () -> new Pill7Item());
	public static final RegistryObject<Item> PILL_8 = REGISTRY.register("pill_8", () -> new Pill8Item());
	public static final RegistryObject<Item> PILL_9 = REGISTRY.register("pill_9", () -> new Pill9Item());
	public static final RegistryObject<Item> PILL_10 = REGISTRY.register("pill_10", () -> new Pill10Item());
	public static final RegistryObject<Item> PILLBOTTLEEMPTY = REGISTRY.register("pillbottleempty", () -> new PillbottleemptyItem());
	public static final RegistryObject<Item> PILLBOTTLE_0 = REGISTRY.register("pillbottle_0", () -> new Pillbottle0Item());
	public static final RegistryObject<Item> PILLBOTTLE_1 = REGISTRY.register("pillbottle_1", () -> new Pillbottle1Item());
	public static final RegistryObject<Item> PILLBOTTLE_2 = REGISTRY.register("pillbottle_2", () -> new Pillbottle2Item());
	public static final RegistryObject<Item> PILLBOTTLE_3 = REGISTRY.register("pillbottle_3", () -> new Pillbottle3Item());
	public static final RegistryObject<Item> PILLBOTTLE_4 = REGISTRY.register("pillbottle_4", () -> new Pillbottle4Item());
	public static final RegistryObject<Item> PILL_BOTTLE_5 = REGISTRY.register("pill_bottle_5", () -> new PillBottle5Item());
	public static final RegistryObject<Item> PILLBOTTLE_6 = REGISTRY.register("pillbottle_6", () -> new Pillbottle6Item());
	public static final RegistryObject<Item> PILLBOTTLE_7 = REGISTRY.register("pillbottle_7", () -> new Pillbottle7Item());
	public static final RegistryObject<Item> PILL_BOTTLE_8 = REGISTRY.register("pill_bottle_8", () -> new PillBottle8Item());
	public static final RegistryObject<Item> PILLBOTTLE_9 = REGISTRY.register("pillbottle_9", () -> new Pillbottle9Item());
	public static final RegistryObject<Item> PILL_BOTTLE_10 = REGISTRY.register("pill_bottle_10", () -> new PillBottle10Item());
	public static final RegistryObject<Item> PILL_11 = REGISTRY.register("pill_11", () -> new Pill11Item());
	public static final RegistryObject<Item> PILL_12 = REGISTRY.register("pill_12", () -> new Pill12Item());
	public static final RegistryObject<Item> PILL_13 = REGISTRY.register("pill_13", () -> new Pill13Item());
	public static final RegistryObject<Item> PILL_14 = REGISTRY.register("pill_14", () -> new Pill14Item());
	public static final RegistryObject<Item> PILL_15 = REGISTRY.register("pill_15", () -> new Pill15Item());
	public static final RegistryObject<Item> PILL_16 = REGISTRY.register("pill_16", () -> new Pill16Item());
	public static final RegistryObject<Item> PILL_17 = REGISTRY.register("pill_17", () -> new Pill17Item());
	public static final RegistryObject<Item> PILL_18 = REGISTRY.register("pill_18", () -> new Pill18Item());
	public static final RegistryObject<Item> PILL_19 = REGISTRY.register("pill_19", () -> new Pill19Item());
	public static final RegistryObject<Item> PILL_20 = REGISTRY.register("pill_20", () -> new Pill20Item());
	public static final RegistryObject<Item> PILLBOTTLE_11 = REGISTRY.register("pillbottle_11", () -> new Pillbottle11Item());
	public static final RegistryObject<Item> PILLBOTTLE_12 = REGISTRY.register("pillbottle_12", () -> new Pillbottle12Item());
	public static final RegistryObject<Item> PILL_BOTTLE_13 = REGISTRY.register("pill_bottle_13", () -> new PillBottle13Item());
	public static final RegistryObject<Item> PILL_BOTTLE_14 = REGISTRY.register("pill_bottle_14", () -> new PillBottle14Item());
	public static final RegistryObject<Item> PILL_BOTTLE_15 = REGISTRY.register("pill_bottle_15", () -> new PillBottle15Item());
	public static final RegistryObject<Item> PILL_BOTTLE_16 = REGISTRY.register("pill_bottle_16", () -> new PillBottle16Item());
	public static final RegistryObject<Item> PILL_BOTTLE_17 = REGISTRY.register("pill_bottle_17", () -> new PillBottle17Item());
	public static final RegistryObject<Item> PILL_BOTTLE_18 = REGISTRY.register("pill_bottle_18", () -> new PillBottle18Item());
	public static final RegistryObject<Item> PILL_BOTTLE_19 = REGISTRY.register("pill_bottle_19", () -> new PillBottle19Item());
	public static final RegistryObject<Item> PILLBOTTLE_20 = REGISTRY.register("pillbottle_20", () -> new Pillbottle20Item());
	public static final RegistryObject<Item> PILL_21 = REGISTRY.register("pill_21", () -> new Pill21Item());
	public static final RegistryObject<Item> PILL_22 = REGISTRY.register("pill_22", () -> new Pill22Item());
	public static final RegistryObject<Item> PILL_23 = REGISTRY.register("pill_23", () -> new Pill23Item());
	public static final RegistryObject<Item> PILL_24 = REGISTRY.register("pill_24", () -> new Pill24Item());
	public static final RegistryObject<Item> PILL_25 = REGISTRY.register("pill_25", () -> new Pill25Item());
	public static final RegistryObject<Item> PILL_26 = REGISTRY.register("pill_26", () -> new Pill26Item());
	public static final RegistryObject<Item> PILL_27 = REGISTRY.register("pill_27", () -> new Pill27Item());
	public static final RegistryObject<Item> PILL_28 = REGISTRY.register("pill_28", () -> new Pill28Item());
	public static final RegistryObject<Item> PILL_29 = REGISTRY.register("pill_29", () -> new Pill29Item());
	public static final RegistryObject<Item> PILL_30 = REGISTRY.register("pill_30", () -> new Pill30Item());
	public static final RegistryObject<Item> PILLBOTTLE_21 = REGISTRY.register("pillbottle_21", () -> new Pillbottle21Item());
	public static final RegistryObject<Item> PILL_BOTTLE_22 = REGISTRY.register("pill_bottle_22", () -> new PillBottle22Item());
	public static final RegistryObject<Item> PILL_BOTTLE_23 = REGISTRY.register("pill_bottle_23", () -> new PillBottle23Item());
	public static final RegistryObject<Item> PILL_BOTTLE_24 = REGISTRY.register("pill_bottle_24", () -> new PillBottle24Item());
	public static final RegistryObject<Item> PILL_BOTTLE_25 = REGISTRY.register("pill_bottle_25", () -> new PillBottle25Item());
	public static final RegistryObject<Item> PILL_BOTTLE_26 = REGISTRY.register("pill_bottle_26", () -> new PillBottle26Item());
	public static final RegistryObject<Item> PILL_BOTTLE_27 = REGISTRY.register("pill_bottle_27", () -> new PillBottle27Item());
	public static final RegistryObject<Item> PILL_BOTTLE_28 = REGISTRY.register("pill_bottle_28", () -> new PillBottle28Item());
	public static final RegistryObject<Item> PILL_BOTTLE_29 = REGISTRY.register("pill_bottle_29", () -> new PillBottle29Item());
	public static final RegistryObject<Item> PILL_BOTTLE_30 = REGISTRY.register("pill_bottle_30", () -> new PillBottle30Item());
	public static final RegistryObject<Item> PILL_31 = REGISTRY.register("pill_31", () -> new Pill31Item());
	public static final RegistryObject<Item> PILL_32 = REGISTRY.register("pill_32", () -> new Pill32Item());
	public static final RegistryObject<Item> PILL_33 = REGISTRY.register("pill_33", () -> new Pill33Item());
	public static final RegistryObject<Item> PILL_34 = REGISTRY.register("pill_34", () -> new Pill34Item());
	public static final RegistryObject<Item> PILL_35 = REGISTRY.register("pill_35", () -> new Pill35Item());
	public static final RegistryObject<Item> PILL_36 = REGISTRY.register("pill_36", () -> new Pill36Item());
	public static final RegistryObject<Item> PILL_37 = REGISTRY.register("pill_37", () -> new Pill37Item());
	public static final RegistryObject<Item> PILL_38 = REGISTRY.register("pill_38", () -> new Pill38Item());
	public static final RegistryObject<Item> PILL_39 = REGISTRY.register("pill_39", () -> new Pill39Item());
	public static final RegistryObject<Item> PILL_40 = REGISTRY.register("pill_40", () -> new Pill40Item());
	public static final RegistryObject<Item> PILL_41 = REGISTRY.register("pill_41", () -> new Pill41Item());
	public static final RegistryObject<Item> PILL_42 = REGISTRY.register("pill_42", () -> new Pill42Item());
	public static final RegistryObject<Item> PILL_43 = REGISTRY.register("pill_43", () -> new Pill43Item());
	public static final RegistryObject<Item> PILL_BOTTLE_31 = REGISTRY.register("pill_bottle_31", () -> new PillBottle31Item());
	public static final RegistryObject<Item> PILL_BOTTLE_32 = REGISTRY.register("pill_bottle_32", () -> new PillBottle32Item());
	public static final RegistryObject<Item> PILL_BOTTLE_33 = REGISTRY.register("pill_bottle_33", () -> new PillBottle33Item());
	public static final RegistryObject<Item> PILL_BOTTLE_34 = REGISTRY.register("pill_bottle_34", () -> new PillBottle34Item());
	public static final RegistryObject<Item> PILL_BOTTLE_35 = REGISTRY.register("pill_bottle_35", () -> new PillBottle35Item());
	public static final RegistryObject<Item> PILL_BOTTLE_36 = REGISTRY.register("pill_bottle_36", () -> new PillBottle36Item());
	public static final RegistryObject<Item> PILL_BOTTLE_37 = REGISTRY.register("pill_bottle_37", () -> new PillBottle37Item());
	public static final RegistryObject<Item> PILL_BOTTLE_38 = REGISTRY.register("pill_bottle_38", () -> new PillBottle38Item());
	public static final RegistryObject<Item> PILL_BOTTLE_39 = REGISTRY.register("pill_bottle_39", () -> new PillBottle39Item());
	public static final RegistryObject<Item> PILL_BOTTLE_40 = REGISTRY.register("pill_bottle_40", () -> new PillBottle40Item());
	public static final RegistryObject<Item> PILL_BOTTLE_41 = REGISTRY.register("pill_bottle_41", () -> new PillBottle41Item());
	public static final RegistryObject<Item> PILL_BOTTLE_42 = REGISTRY.register("pill_bottle_42", () -> new PillBottle42Item());
	public static final RegistryObject<Item> PILL_BOTTLE_43 = REGISTRY.register("pill_bottle_43", () -> new PillBottle43Item());
	public static final RegistryObject<Item> SMALL_MEDKIT = REGISTRY.register("small_medkit", () -> new SmallMedkitItem());
	public static final RegistryObject<Item> LARGEMEDKIT = REGISTRY.register("largemedkit", () -> new LargemedkitItem());
	public static final RegistryObject<Item> LIGHT_BLOCK = block(HospitalsModBlocks.LIGHT_BLOCK);
	public static final RegistryObject<Item> STAINLESS_STEEL = REGISTRY.register("stainless_steel", () -> new StainlessSteelItem());
	public static final RegistryObject<Item> BLOCK_OF_STAINLESS_STEEL = block(HospitalsModBlocks.BLOCK_OF_STAINLESS_STEEL);
	public static final RegistryObject<Item> UNPROCESSED_STEEL = REGISTRY.register("unprocessed_steel", () -> new UnprocessedSteelItem());
	public static final RegistryObject<Item> COMPUTER_CHIP = REGISTRY.register("computer_chip", () -> new ComputerChipItem());
	public static final RegistryObject<Item> COMPUTER = REGISTRY.register("computer", () -> new ComputerItem());
	public static final RegistryObject<Item> MASK_HELMET = REGISTRY.register("mask_helmet", () -> new ScrubmaskItem.Helmet());
	public static final RegistryObject<Item> CREATIVE_PILL = REGISTRY.register("creative_pill", () -> new CreativePillItem());
	public static final RegistryObject<Item> WARNING = block(HospitalsModBlocks.WARNING);
	public static final RegistryObject<Item> BLOODBAGONEGATIVE = REGISTRY.register("bloodbagonegative", () -> new BloodbagonegativeItem());
	public static final RegistryObject<Item> BLOODBAGOPOSITIVE = REGISTRY.register("bloodbagopositive", () -> new BloodbagopositiveItem());
	public static final RegistryObject<Item> BLOODBAGBNEGATIVE = REGISTRY.register("bloodbagbnegative", () -> new BloodbagbnegativeItem());
	public static final RegistryObject<Item> BLOODBAGBPOSITIVE = REGISTRY.register("bloodbagbpositive", () -> new BloodbagbpositiveItem());
	public static final RegistryObject<Item> BLOODBAGANEGATIVE = REGISTRY.register("bloodbaganegative", () -> new BloodbaganegativeItem());
	public static final RegistryObject<Item> BLOODBAGAPOSITIVE = REGISTRY.register("bloodbagapositive", () -> new BloodbagapositiveItem());
	public static final RegistryObject<Item> BLOODBAGABNEGATIVE = REGISTRY.register("bloodbagabnegative", () -> new BloodbagabnegativeItem());
	public static final RegistryObject<Item> BLOODBAGABPOSITIVE = REGISTRY.register("bloodbagabpositive", () -> new BloodbagabpositiveItem());
	public static final RegistryObject<Item> BLOODBAGEMPTY = REGISTRY.register("bloodbagempty", () -> new BloodbagemptyItem());
	public static final RegistryObject<Item> EMPTY_SYRINGE = REGISTRY.register("empty_syringe", () -> new EmptySyringeItem());
	public static final RegistryObject<Item> SYRINGEBLOOD_ONEGATIVE = REGISTRY.register("syringeblood_onegative", () -> new SyringebloodOnegativeItem());
	public static final RegistryObject<Item> SYRINGE_BLOOD_O_POSITIVE = REGISTRY.register("syringe_blood_o_positive", () -> new SyringeBloodOPositiveItem());
	public static final RegistryObject<Item> SYRINGE_BLOOD_B_NEGATIVE = REGISTRY.register("syringe_blood_b_negative", () -> new SyringeBloodBNegativeItem());
	public static final RegistryObject<Item> SYRINGE_BLOOD_B_POSITIVE = REGISTRY.register("syringe_blood_b_positive", () -> new SyringeBloodBPositiveItem());
	public static final RegistryObject<Item> SYRINGE_BLOOD_A_NEGATIVE = REGISTRY.register("syringe_blood_a_negative", () -> new SyringeBloodANegativeItem());
	public static final RegistryObject<Item> SYRINGE_BLOOD_A_POSITIVE = REGISTRY.register("syringe_blood_a_positive", () -> new SyringeBloodAPositiveItem());
	public static final RegistryObject<Item> SYRINGE_BLOOD_AB_NEGATIVE = REGISTRY.register("syringe_blood_ab_negative", () -> new SyringeBloodABNegativeItem());
	public static final RegistryObject<Item> SYRINGE_BLOOD_AB_POSITIVE = REGISTRY.register("syringe_blood_ab_positive", () -> new SyringeBloodABPositiveItem());
	public static final RegistryObject<Item> SYRINGE_BLOOD_MIXED = REGISTRY.register("syringe_blood_mixed", () -> new SyringeBloodMixedItem());
	public static final RegistryObject<Item> BLOOD_CENTRIFUGE = block(HospitalsModBlocks.BLOOD_CENTRIFUGE);

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return block(block, new Item.Properties());
	}

	private static RegistryObject<Item> block(RegistryObject<Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}
}