
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.derpymeow.hospitals.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.derpymeow.hospitals.item.ScrubsItem;
import net.derpymeow.hospitals.item.PillItem;
import net.derpymeow.hospitals.HospitalsMod;

public class HospitalsModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, HospitalsMod.MODID);
	public static final RegistryObject<Item> TH_BLOCK = block(HospitalsModBlocks.TH_BLOCK);
	public static final RegistryObject<Item> PH_BLOCK = block(HospitalsModBlocks.PH_BLOCK);
	public static final RegistryObject<Item> RA_BLOCK = block(HospitalsModBlocks.RA_BLOCK);
	public static final RegistryObject<Item> WA_BLOCK = block(HospitalsModBlocks.WA_BLOCK);
	public static final RegistryObject<Item> FA_BLOCK = block(HospitalsModBlocks.FA_BLOCK);
	public static final RegistryObject<Item> MEDICAL_CROSS = block(HospitalsModBlocks.MEDICAL_CROSS);
	public static final RegistryObject<Item> ANAESTHETIC_MACHINE = block(HospitalsModBlocks.ANAESTHETIC_MACHINE);
	public static final RegistryObject<Item> SURGICAL_REFRIDGERATED_CABINET = block(HospitalsModBlocks.SURGICAL_REFRIDGERATED_CABINET);
	public static final RegistryObject<Item> SURGICAL_WORKTOP_TABLE = block(HospitalsModBlocks.SURGICAL_WORKTOP_TABLE);
	public static final RegistryObject<Item> SURGICAL_INSTRUMENT_TROLLEY = block(HospitalsModBlocks.SURGICAL_INSTRUMENT_TROLLEY);
	public static final RegistryObject<Item> OPERATING_TABLE = block(HospitalsModBlocks.OPERATING_TABLE);
	public static final RegistryObject<Item> SCRUB_SINK = block(HospitalsModBlocks.SCRUB_SINK);
	public static final RegistryObject<Item> WALL_STORAGE_TUBS_RED = block(HospitalsModBlocks.WALL_STORAGE_TUBS_RED);
	public static final RegistryObject<Item> WALL_STORAGE_TUBS_YELLOW = block(HospitalsModBlocks.WALL_STORAGE_TUBS_YELLOW);
	public static final RegistryObject<Item> SURGICAL_LAMP = block(HospitalsModBlocks.SURGICAL_LAMP);
	public static final RegistryObject<Item> SURGICAL_TROLLEY = block(HospitalsModBlocks.SURGICAL_TROLLEY);
	public static final RegistryObject<Item> STERILE_WORKTOP = block(HospitalsModBlocks.STERILE_WORKTOP);
	public static final RegistryObject<Item> STERILE_WORK_COUNTER_WITH_SHELF = block(HospitalsModBlocks.STERILE_WORK_COUNTER_WITH_SHELF);
	public static final RegistryObject<Item> SURGICAL_WORKSTATION = block(HospitalsModBlocks.SURGICAL_WORKSTATION);
	public static final RegistryObject<Item> OPERATING_ROOM_CONTROL_PANEL = block(HospitalsModBlocks.OPERATING_ROOM_CONTROL_PANEL);
	public static final RegistryObject<Item> SURGICAL_INSTRUMENTS = block(HospitalsModBlocks.SURGICAL_INSTRUMENTS);
	public static final RegistryObject<Item> MEDICAL_GAS_CEILING_MOUNTED = block(HospitalsModBlocks.MEDICAL_GAS_CEILING_MOUNTED);
	public static final RegistryObject<Item> ILLUMINATED_PHARMACY_SIGN = block(HospitalsModBlocks.ILLUMINATED_PHARMACY_SIGN);
	public static final RegistryObject<Item> STORE_SHELF_EMPTY = block(HospitalsModBlocks.STORE_SHELF_EMPTY);
	public static final RegistryObject<Item> STORE_SHELF_STOCKED = block(HospitalsModBlocks.STORE_SHELF_STOCKED);
	public static final RegistryObject<Item> COMPOUNDING_ISOLATOR = block(HospitalsModBlocks.COMPOUNDING_ISOLATOR);
	public static final RegistryObject<Item> ANALYTICAL_BALANCE = block(HospitalsModBlocks.ANALYTICAL_BALANCE);
	public static final RegistryObject<Item> REFRIDGERATED_CENTRIFUGE = block(HospitalsModBlocks.REFRIDGERATED_CENTRIFUGE);
	public static final RegistryObject<Item> WORKTOP_WITH_SHELF = block(HospitalsModBlocks.WORKTOP_WITH_SHELF);
	public static final RegistryObject<Item> WORKTOP = block(HospitalsModBlocks.WORKTOP);
	public static final RegistryObject<Item> LABORATORY_FRIDGE = block(HospitalsModBlocks.LABORATORY_FRIDGE);
	public static final RegistryObject<Item> CAPSULE_FILLING_MACHINE = block(HospitalsModBlocks.CAPSULE_FILLING_MACHINE);
	public static final RegistryObject<Item> BOTTLE_FILLING_MACHINE = block(HospitalsModBlocks.BOTTLE_FILLING_MACHINE);
	public static final RegistryObject<Item> MEDICATION_DRAWERS = block(HospitalsModBlocks.MEDICATION_DRAWERS);
	public static final RegistryObject<Item> PRESCRIPTION_SHELF = block(HospitalsModBlocks.PRESCRIPTION_SHELF);
	public static final RegistryObject<Item> EPOS_CASHIER_SYSTEM = block(HospitalsModBlocks.EPOS_CASHIER_SYSTEM);
	public static final RegistryObject<Item> PRESCRIPTION_BASKET_EMPTY = block(HospitalsModBlocks.PRESCRIPTION_BASKET_EMPTY);
	public static final RegistryObject<Item> PRESCRIPTION_BASKET = block(HospitalsModBlocks.PRESCRIPTION_BASKET);
	public static final RegistryObject<Item> PHARMACY_COUNTER_STOCKED = block(HospitalsModBlocks.PHARMACY_COUNTER_STOCKED);
	public static final RegistryObject<Item> PHARMACY_COUNTERWITH_LOGO = block(HospitalsModBlocks.PHARMACY_COUNTERWITH_LOGO);
	public static final RegistryObject<Item> PHARMACY_COUNTER = block(HospitalsModBlocks.PHARMACY_COUNTER);
	public static final RegistryObject<Item> DECORATIVE_DIVIDE = block(HospitalsModBlocks.DECORATIVE_DIVIDE);
	public static final RegistryObject<Item> ULTRASOUND = block(HospitalsModBlocks.ULTRASOUND);
	public static final RegistryObject<Item> X_RAY_LIGHT = block(HospitalsModBlocks.X_RAY_LIGHT);
	public static final RegistryObject<Item> XRAY_LIGHT_BOX_BLANK = block(HospitalsModBlocks.XRAY_LIGHT_BOX_BLANK);
	public static final RegistryObject<Item> XRAY_LIGHT_BOX_CHEST = block(HospitalsModBlocks.XRAY_LIGHT_BOX_CHEST);
	public static final RegistryObject<Item> XRAY_LIGHT_BOX_FEET = block(HospitalsModBlocks.XRAY_LIGHT_BOX_FEET);
	public static final RegistryObject<Item> XRAY_LIGHT_BOX_HANDS = block(HospitalsModBlocks.XRAY_LIGHT_BOX_HANDS);
	public static final RegistryObject<Item> XRAY_LIGHT_BOX_ARMS = block(HospitalsModBlocks.XRAY_LIGHT_BOX_ARMS);
	public static final RegistryObject<Item> XRAY_LIGHT_BOX_NECK = block(HospitalsModBlocks.XRAY_LIGHT_BOX_NECK);
	public static final RegistryObject<Item> X_RAY_MACHINE = block(HospitalsModBlocks.X_RAY_MACHINE);
	public static final RegistryObject<Item> XRAY_BUCKY_STAND = block(HospitalsModBlocks.XRAY_BUCKY_STAND);
	public static final RegistryObject<Item> COMPUTER_CT_SCAN_VIEWER = block(HospitalsModBlocks.COMPUTER_CT_SCAN_VIEWER);
	public static final RegistryObject<Item> COMPUTER_X_RAY_VIEWER = block(HospitalsModBlocks.COMPUTER_X_RAY_VIEWER);
	public static final RegistryObject<Item> COMPUTER_SCREEN_2_CT_SCAN_VIEWER = block(HospitalsModBlocks.COMPUTER_SCREEN_2_CT_SCAN_VIEWER);
	public static final RegistryObject<Item> COMPUTER_SCREEN_2_XRAY_VIEWER = block(HospitalsModBlocks.COMPUTER_SCREEN_2_XRAY_VIEWER);
	public static final RegistryObject<Item> BEDSIDE_HEAD_UNIT = block(HospitalsModBlocks.BEDSIDE_HEAD_UNIT);
	public static final RegistryObject<Item> WARD_STORAGE_DRAWERS = block(HospitalsModBlocks.WARD_STORAGE_DRAWERS);
	public static final RegistryObject<Item> FETAL_MONITORING_WORKSTATION = block(HospitalsModBlocks.FETAL_MONITORING_WORKSTATION);
	public static final RegistryObject<Item> HOSPITAL_BED = block(HospitalsModBlocks.HOSPITAL_BED);
	public static final RegistryObject<Item> IV_STAND = block(HospitalsModBlocks.IV_STAND);
	public static final RegistryObject<Item> MEDICAL_WORKSTATION_CART = block(HospitalsModBlocks.MEDICAL_WORKSTATION_CART);
	public static final RegistryObject<Item> LIFE_SUPPORT_SYRINGE_PUMPS = block(HospitalsModBlocks.LIFE_SUPPORT_SYRINGE_PUMPS);
	public static final RegistryObject<Item> HEART_RATE_MONITOR = block(HospitalsModBlocks.HEART_RATE_MONITOR);
	public static final RegistryObject<Item> WARD_RESUS_TROLLEY = block(HospitalsModBlocks.WARD_RESUS_TROLLEY);
	public static final RegistryObject<Item> MEDICAL_GAS_ALARM_PANEL = block(HospitalsModBlocks.MEDICAL_GAS_ALARM_PANEL);
	public static final RegistryObject<Item> HAND_SANITISER_DISPENSER = block(HospitalsModBlocks.HAND_SANITISER_DISPENSER);
	public static final RegistryObject<Item> RACK_SHELVING_EMPTY = block(HospitalsModBlocks.RACK_SHELVING_EMPTY);
	public static final RegistryObject<Item> RACK_SHELVES_LINEN = block(HospitalsModBlocks.RACK_SHELVES_LINEN);
	public static final RegistryObject<Item> FIRE_EXIT_SIGN_CEILING_MOUNTED = block(HospitalsModBlocks.FIRE_EXIT_SIGN_CEILING_MOUNTED);
	public static final RegistryObject<Item> FIRE_EXIT_SIGN_WALL_MOUNTED = block(HospitalsModBlocks.FIRE_EXIT_SIGN_WALL_MOUNTED);
	public static final RegistryObject<Item> FIRE_EXTINGUISHER = block(HospitalsModBlocks.FIRE_EXTINGUISHER);
	public static final RegistryObject<Item> PATIENT_INFORMAITON_POINT = block(HospitalsModBlocks.PATIENT_INFORMAITON_POINT);
	public static final RegistryObject<Item> ROLL_CAGE_STORAGE = block(HospitalsModBlocks.ROLL_CAGE_STORAGE);
	public static final RegistryObject<Item> SUSPENDED_CEILING = block(HospitalsModBlocks.SUSPENDED_CEILING);
	public static final RegistryObject<Item> VINYL_FLOOR_BLUE_TYPE_1 = block(HospitalsModBlocks.VINYL_FLOOR_BLUE_TYPE_1);
	public static final RegistryObject<Item> VINYL_FLOOR_GREY_TYPE_1 = block(HospitalsModBlocks.VINYL_FLOOR_GREY_TYPE_1);
	public static final RegistryObject<Item> VINYL_FLOOR_WHITE_TYPE_1 = block(HospitalsModBlocks.VINYL_FLOOR_WHITE_TYPE_1);
	public static final RegistryObject<Item> VINYL_FLOOR_LIGHT_BLUE_TYPE_1 = block(HospitalsModBlocks.VINYL_FLOOR_LIGHT_BLUE_TYPE_1);
	public static final RegistryObject<Item> VINYL_FLOOR_GREEN_TYPE_1 = block(HospitalsModBlocks.VINYL_FLOOR_GREEN_TYPE_1);
	public static final RegistryObject<Item> VINYL_FLOOR_AQUA_TYPE_1 = block(HospitalsModBlocks.VINYL_FLOOR_AQUA_TYPE_1);
	public static final RegistryObject<Item> VINYL_FLOOR_RED_TYPE_1 = block(HospitalsModBlocks.VINYL_FLOOR_RED_TYPE_1);
	public static final RegistryObject<Item> VINYL_WALL_BLUE_TYPE_1 = block(HospitalsModBlocks.VINYL_WALL_BLUE_TYPE_1);
	public static final RegistryObject<Item> VINYL_WALL_GREY_TYPE_1 = block(HospitalsModBlocks.VINYL_WALL_GREY_TYPE_1);
	public static final RegistryObject<Item> VINYL_WALL_WHITE_TYPE_1 = block(HospitalsModBlocks.VINYL_WALL_WHITE_TYPE_1);
	public static final RegistryObject<Item> VINYL_WALL_LIGHT_BLUE_TYPE_1 = block(HospitalsModBlocks.VINYL_WALL_LIGHT_BLUE_TYPE_1);
	public static final RegistryObject<Item> VINYL_WALL_GREEN_TYPE_1 = block(HospitalsModBlocks.VINYL_WALL_GREEN_TYPE_1);
	public static final RegistryObject<Item> VINYL_WALL_AQUA_TYPE_1 = block(HospitalsModBlocks.VINYL_WALL_AQUA_TYPE_1);
	public static final RegistryObject<Item> VINYL_WALL_RED_TYPE_1 = block(HospitalsModBlocks.VINYL_WALL_RED_TYPE_1);
	public static final RegistryObject<Item> VINYL_FLOOR_BLUE_TYPE_2 = block(HospitalsModBlocks.VINYL_FLOOR_BLUE_TYPE_2);
	public static final RegistryObject<Item> VINYL_FLOOR_BEIGE_TYPE_2 = block(HospitalsModBlocks.VINYL_FLOOR_BEIGE_TYPE_2);
	public static final RegistryObject<Item> VINYL_FLOOR_GREY_TYPE_2 = block(HospitalsModBlocks.VINYL_FLOOR_GREY_TYPE_2);
	public static final RegistryObject<Item> VINYL_FLOOR_AQUA_TYPE_2 = block(HospitalsModBlocks.VINYL_FLOOR_AQUA_TYPE_2);
	public static final RegistryObject<Item> VINYL_FLOOR_SALMON_TYPE_2 = block(HospitalsModBlocks.VINYL_FLOOR_SALMON_TYPE_2);
	public static final RegistryObject<Item> VINYL_WALL_BLUE_TYPE_2 = block(HospitalsModBlocks.VINYL_WALL_BLUE_TYPE_2);
	public static final RegistryObject<Item> VINYL_WALL_BEIGE_TYPE_2 = block(HospitalsModBlocks.VINYL_WALL_BEIGE_TYPE_2);
	public static final RegistryObject<Item> VINYL_WALL_GREY_TYPE_2 = block(HospitalsModBlocks.VINYL_WALL_GREY_TYPE_2);
	public static final RegistryObject<Item> VINYL_WALL_AQUA_TYPE_2 = block(HospitalsModBlocks.VINYL_WALL_AQUA_TYPE_2);
	public static final RegistryObject<Item> VINYL_WALL_SALMON_TYPE_2 = block(HospitalsModBlocks.VINYL_WALL_SALMON_TYPE_2);
	public static final RegistryObject<Item> BRICK_BEIGE = block(HospitalsModBlocks.BRICK_BEIGE);
	public static final RegistryObject<Item> BRICK_GREY = block(HospitalsModBlocks.BRICK_GREY);
	public static final RegistryObject<Item> BRICK_DARK = block(HospitalsModBlocks.BRICK_DARK);
	public static final RegistryObject<Item> BRICK_RED = block(HospitalsModBlocks.BRICK_RED);
	public static final RegistryObject<Item> SMOOTH_CONCRETE = block(HospitalsModBlocks.SMOOTH_CONCRETE);
	public static final RegistryObject<Item> PLASTERED_WALL_BEIGE = block(HospitalsModBlocks.PLASTERED_WALL_BEIGE);
	public static final RegistryObject<Item> PLASTERED_WALL_BLUE = block(HospitalsModBlocks.PLASTERED_WALL_BLUE);
	public static final RegistryObject<Item> PLASTERED_WALL_GREEN = block(HospitalsModBlocks.PLASTERED_WALL_GREEN);
	public static final RegistryObject<Item> PLASTERED_WALL_GREY = block(HospitalsModBlocks.PLASTERED_WALL_GREY);
	public static final RegistryObject<Item> PLASTERED_WALL_LIME = block(HospitalsModBlocks.PLASTERED_WALL_LIME);
	public static final RegistryObject<Item> PLASTERED_WALL_SKY_BLUE = block(HospitalsModBlocks.PLASTERED_WALL_SKY_BLUE);
	public static final RegistryObject<Item> PLASTERED_WALL_WHITE = block(HospitalsModBlocks.PLASTERED_WALL_WHITE);
	public static final RegistryObject<Item> VENTILATION = block(HospitalsModBlocks.VENTILATION);
	public static final RegistryObject<Item> CARDBOARD_BOX = block(HospitalsModBlocks.CARDBOARD_BOX);
	public static final RegistryObject<Item> VINYL_FLOOR_GREY = block(HospitalsModBlocks.VINYL_FLOOR_GREY);
	public static final RegistryObject<Item> CLADDING_STONE_EFFECT = block(HospitalsModBlocks.CLADDING_STONE_EFFECT);
	public static final RegistryObject<Item> BLUE_DESK_TRAY = block(HospitalsModBlocks.BLUE_DESK_TRAY);
	public static final RegistryObject<Item> RED_DESK_TRAY = block(HospitalsModBlocks.RED_DESK_TRAY);
	public static final RegistryObject<Item> DRINKS_FRIDGE = block(HospitalsModBlocks.DRINKS_FRIDGE);
	public static final RegistryObject<Item> CLEANING_TROLLEY = block(HospitalsModBlocks.CLEANING_TROLLEY);
	public static final RegistryObject<Item> WET_FLOOR_SIGN = block(HospitalsModBlocks.WET_FLOOR_SIGN);
	public static final RegistryObject<Item> OFFICE_WALL_PHONE = block(HospitalsModBlocks.OFFICE_WALL_PHONE);
	public static final RegistryObject<Item> OFFICE_DESK_PHONE = block(HospitalsModBlocks.OFFICE_DESK_PHONE);
	public static final RegistryObject<Item> OFFICE_PRINTER = block(HospitalsModBlocks.OFFICE_PRINTER);
	public static final RegistryObject<Item> OFFICE_DESK = block(HospitalsModBlocks.OFFICE_DESK);
	public static final RegistryObject<Item> OFFICE_DESK_WITH_BACK = block(HospitalsModBlocks.OFFICE_DESK_WITH_BACK);
	public static final RegistryObject<Item> WASTE_BIN_DOMESTIC_WASTE = block(HospitalsModBlocks.WASTE_BIN_DOMESTIC_WASTE);
	public static final RegistryObject<Item> WASTE_BIN_CLINICAL_WASTE = block(HospitalsModBlocks.WASTE_BIN_CLINICAL_WASTE);
	public static final RegistryObject<Item> PILL = REGISTRY.register("pill", () -> new PillItem());
	public static final RegistryObject<Item> SCRUBS_HELMET = REGISTRY.register("scrubs_helmet", () -> new ScrubsItem.Helmet());
	public static final RegistryObject<Item> SCRUBS_CHESTPLATE = REGISTRY.register("scrubs_chestplate", () -> new ScrubsItem.Chestplate());
	public static final RegistryObject<Item> SCRUBS_LEGGINGS = REGISTRY.register("scrubs_leggings", () -> new ScrubsItem.Leggings());
	public static final RegistryObject<Item> SCRUBS_BOOTS = REGISTRY.register("scrubs_boots", () -> new ScrubsItem.Boots());
	public static final RegistryObject<Item> NURSE_SPAWN_EGG = REGISTRY.register("nurse_spawn_egg", () -> new ForgeSpawnEggItem(HospitalsModEntities.NURSE, -1, -39220, new Item.Properties()));
	public static final RegistryObject<Item> DOCTOR_SPAWN_EGG = REGISTRY.register("doctor_spawn_egg", () -> new ForgeSpawnEggItem(HospitalsModEntities.DOCTOR, -1, -52429, new Item.Properties()));

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
